### ISSUE TITLE
Clarify which version of XHR is required

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#1]
The [spec text](https://github.com/w3c/webmediaapi/blob/gh-pages/index.html#L139) requires "XMLHttpRequest Level 1", but the reference inserted by respec is to the [WHATWG Living Standard](https://xhr.spec.whatwg.org/) which is continually updated and makes no mention of "Level 1".

The W3C [spec](https://www.w3.org/TR/XMLHttpRequest/) points the WHATWG, or a [2014 Working Draft](https://www.w3.org/TR/2014/WD-XMLHttpRequest-20140130/).

We should clarify what exactly is required here. I would very much like to see at least some of the WHATWG changes (particularly responseUrl), but that leads to a wider question: are we able to reference continually updating standards or do we need to select a dated version?

**Comment by tidoust** [comment]
Right. I would drop "Level 1" and keep the reference to the WHATWG spec.

I note that HTML5.1 [references the XMLHttpRequest Living Standard](http://www.w3.org/TR/html51/references.html#biblio-xhr). The fact that the spec is continually updated does not mean that it is unstable.

**Comment by jpiesing** [comment]
I think there does need to be a discussion about what it means to test & certify against a living standard & what guarantees that gives to content providers (if any).

**Comment by mavgit** [comment]
If the implementations are currently following the WHATWG XHR spec, I think it makes no sense to reference an older spec.

(I agree with @jpiesing that we should discuss the test & certification issues with referencing WHATWG documents.)

**Comment by mavgit** [comment]
**Call for consensus:** Don't specify Level 1 for XHR support. #8 
Please comment if you disagree. Silence is taken as consent.
We'll apply changes after the upcoming F2F.

**Comment by jpiesing** [comment]
I don't agree to referencing WHATWG without some versioning.

**Comment by mavgit** [comment]
@jpiesing I agree that we need to specify a "no earlier than" dated version of any non-final spec or WHATWG living spec. What we did with the Comcast spec list is to mark each spec reference as FINAL or NON-FINAL. For example:

>[MSE]	W3C, Media Source Extensions, W3C Candidate Recommendation 12 November 2015, http://www.w3.org/TR/media-source , NON-FINAL

The NON-FINAL specs referenced a dated spec version that was the oldest version that could be supported. We then we added language:

>When a Normative Requirement is marked FINAL, it is necessary to conform to all requirements included in the referenced work unless otherwise specifically indicated by the requirements of this specification. When a Normative Requirement is marked NON-FINAL, it is necessary to work in good faith to implement the requirements included in the latest published version.

This encourages clients to keep up to date with any spec still moving towards final, without micromanaging their update timing.

@tidoust said:
>The fact that the spec is continually updated does not mean that it is unstable.

I agree. We need to look at each non-final reference and each living spec reference on a case-by-case basis wrt stability and support.

**Comment by jpiesing** [comment]
@mavgit What triggered my particular concerns about this reference was the comment from @bbcrddave that;
> We should clarify what exactly is required here. I would very much like to see at least some of the WHATWG changes (particularly responseUrl), 

We need to be clear whether that is required or not.

**Comment by poolec** [comment]
Face to face 15/12/2016:
Agreed to remove level 1 (i.e. reference WHATWG) but also add a minimum date.  Date would ideally be at a convenient stable point in the recent past, rather than today's date.

**Comment by davemevans** [comment]
08/02:
Editors to pick a date/commit which is deemed to be stable and make a specref entry, then make the edit as a result.

**Comment by mavgit** [comment]
The consensus seems to be to add a dated reference to this spec which is currently in WHATWG. The editors are currently investigating the best way to provide this reference.

**Comment by davemevans** [comment]
The only way to reference a dated version of a WHATWG spec seems to be to use a commit snapshot. The earliest commit snapshot of the XHR spec is 22nd January 2017. If this is not early enough to satisfy https://github.com/w3c/webmediaapi/issues/1#issuecomment-267498591 then this is not a viable way forward.

It is worth noting that commit snapshots include a warning as follows: **Do not attempt to implement this version of the specification. Do not reference this version as authoritative in any way.**

**Comment by mavgit** [comment]
HTML 5.1, which is our fundamental reference, includes undated references to WHATWG specs, for example the Fetch API; HTML 5.1 uses the [FETCH] reference from SpecRef.

https://www.w3.org/TR/html51/single-page.html#normative

Therefore, this spec unavoidably must already include indirect references to undated WHATWG specs. Therefore, I think we must follow the W3C model and use the standard WHATWG document references from SpecRef for all our additional WHATWG references.

**Comment by mavgit** [comment]
Call for Consensus to reference XHR by the SpecRef standard reference [XHR]:

"[XHR]
Anne van Kesteren. XMLHttpRequest Standard. Living Standard. URL: https://xhr.spec.whatwg.org/"

**Comment by davemevans** [comment]
PR #8 should close this by removing "Level 1" from the requirement - we already reference [XHR].

**Comment by joeyparrish** [comment]
If "level 1" is nonsense, dropping it is objectively better than not.  I say we should merge PR #8.

As for questions about what version to specify instead, responseUrl (which is extremely useful) was introduced on Feb 7, 2014: https://github.com/whatwg/xhr/commit/0c967018

Since the only XHR feature called out is more than 3 years old and there's a nasty-gram at the top of any snapshot, I think it would suffice to drop "level 1" for now.

At most, we could mention somewhere that responseUrl is a required feature, and add a test for it to the test suite.  But I think debating this point should not hold up the simple and clear improvement of dropping "level 1".  We should merge PR #8 regardless.

**Comment by davemevans** [comment]
Consensus reached on telco 03/05/17.
