### ISSUE TITLE
Make EME conditional on CDM support

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#103]
Currently, support for EME is listed as mandatory. I suggest EME should instead be conditionally mandatory on the existence of a CDM (Content Decryption Module) in the device.

This way, if a device manufacturer chooses to not support a CDM in their device, then they do not need to support the EME API, which would have no purpose on that device.

**Comment by davemevans** [comment]
I disagree.

For some content providers, on some platforms, Clearkey is an acceptable and useful content protection mechanism and support for this is theoretically mandatory for EME implementations.

HBBTV, for example, mandates support for EME with Clearkey.

**Comment by mavgit** [comment]
Consensus on call to close this issue with no change.
