### ISSUE TITLE
Support Content Security Policy spec

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#104]
I think we should support the Content Security Policy spec, either 1 or both 1 and 2. These provide important security functions to build reliable media web apps. I think it was an oversight not to include CSP.

CanIUse shows CSP 1 has been long supported on all platforms and that CSP 2 is supported on all platforms, with the exception of one API on Gecko.
- http://caniuse.com/#search=content%20security%20policy

**Comment by davemevans** [comment]
CSP2 is included in https://w3c.github.io/webmediaapi/#security-specifications?
