### ISSUE TITLE
Add Geolocation API to list?

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#110]
The W3C Geolocation API is used for some non-mobile use cases related to streaming video services:
- local movie theater tickets & showtimes
- local or regional news or sports
- local advertisements
- blackouts
- etc.

These use cases are relevant to both mobile and non-mobile devices, like TVs.

Note that the Geolocation API has no hardware requirements. It can be implemented as an interface to hardware or as pure software:
>The API itself is agnostic of the underlying location information sources. Common sources of location information include Global Positioning System (GPS) and location inferred from network signals such as IP address, RFID, WiFi and Bluetooth MAC addresses, and GSM/CDMA cell IDs, as well as user input.
https://www.w3.org/TR/geolocation-API/#introduction

Geolocation API is supported in all our web client code bases: https://caniuse.com/#search=geolocation

I'm not sure whether Geolocation API should be required or not, but I thought it should be discussed.

**Comment by jpiesing** [comment]
In other places, manufacturers of devices that don't already have built-in support for geolocation objected to this quite strongly. Yes it is possible to implement this to some extent using IP-based geolocation but it was suggested that these services aren't free & so a working implementation of this API would cost real money.

**Comment by mavgit** [comment]
Could we hear from folks familiar with any of the user agent code bases (Blink/Chromium, Edge, Gecko, WebKit) about the availability of software-based geolocation?
1. Does the user agent code base include code for software-based geolocation?
2. Are there any available external libraries or services for software-based geolocation?

**Comment by jpiesing** [comment]
Sept 19th meeting
Discussion
- Why is it necessary to for media playback?
- If this matters to a content provider, surely they would use a service they had a contract with and not some unknown service with a potentially unknown accuracy & quality
- It could be quite easy to hack
- What other use-cases are there? Sports black-out? Country based rights? Location-based targeted ads?
- 1st two use-case would need a known reliable service
- Major sudios are very serious about their geolocation
- Is a mandatory geolocation API with unknown underlying quality useful to anyone?
- From a web developer API will check that the API is support
- Nobody will remove the API, it just won't return useful information if there's no underlying implementation
- What about privacy?
- Desktop browsers send wifi network details to a location service if you enable this
- May become more robust in the future but not now
- Moving to more AI based heuristics
- This is a problem that does not need to be solved here
Conclusion
- We will say nothing about this in v1.
