### ISSUE TITLE
suggestion from IBC f2f

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#113]
During the face to face meeting at IBC, it was suggested we might add something to the introduction that there's no suggestion that APIs not mentioned in the spec are expected to be removed if they happen to be supported by a particular UA code base.

**Comment by davemevans** [comment]
Sounds very sensible. Did any propose any text? :wink:

**Comment by mavgit** [comment]
Here's a strawman:

>This specification summarizes a broad set of APIs that are included in all major code bases and that will be the basis of a set of tests to verify inclusion. However, this specification is not a complete definition of the Web platform. There may be additional specifications that are included in all code bases that are not included in this specification. Furthermore, individual code bases include APIs that are not supported on all other code bases, but are nonetheless widely used. Therefore, this specification and associated tests should only be used as verification of a minimum set of required APIs. There is no suggestion that APIs not included in this specification should be removed from implementations.

**Comment by davemevans** [comment]
Consensus reached on 18/10 telco to merge text in https://github.com/w3c/webmediaapi/issues/113#issuecomment-335502926.
