### ISSUE TITLE
Title of Section 3.1.1 confusing in context of Section 3

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#114]
The title of section 3.1.1 is a little confusing.

Section 3 is titled:
>  Web Media APIs currently supported on all platforms

and within it, we have:

> 3.1.1 APIs not widely implemented across all web platforms

which is a bit odd - with APIs in the heading it feels like it shouldn't be in section 3 (probably because it used to be in its own top-level section :wink:)

3.1.1 should probably be something like "Features with limited deployment", or something else that doesn't sound like the inverse of the wider section title.  "Features" seems sensible because that is used in the text and also matches 3.1.2.

I'll come up with some text and we can discuss what to do on the call.

EDIT: The first instance of "API" in the final sentence of 3.1.1 should probably also be substituted for "features" or similar.

**Comment by mavgit** [comment]
You propose: 
> **Features with limited implementation**
When requiring conformance to a specification in this section, it must be recognised that parts of some web specifications are not currently implemented across all web platforms and may never be. Consequently, these features may not be present in some implementations of this specification and will not be tested as part of our tests. Any such **features** are noted as exceptions under that API.

These changes are good and minimal. I also note that the paragraph is a bit repetitive and therefore unclear. Here's a proposal for tightening the text:

> Features with limited implementation
Parts of some web specifications are not currently implemented across all web platforms and may never be. Consequently, these features will not be included in our tests. Any such features are noted as exceptions under that API.

**Comment by davemevans** [comment]
I think your suggestion improves the paragraph overall. I decided against making more than the absolute minimum changes since I recall this text being contentious the first time round, but I think it's worth revisiting.

**Comment by davemevans** [comment]
Consensus reached on 18/10 telco to merge PR #115.
