### ISSUE TITLE
Conformance testing of the Web Media API Snapshot spec

### ISSUE THREAD

**Issue by andyburras** [w3c-cg/webmediaapi#116]
_[Moved from porting spec issues]_

> Since these likely all relate to specs that are included in the Web Media API Snapshot spec, this work could also just be part of the testing effort for the API Snapshot spec

I think there may be an issue here for conformance testing. Currently the Web Media API Snapshot spec is mainly a reference to a large number of W3C specifications in their entirety (aside from a few "Exceptions" clauses). However, my understanding is that none of the four major browsers would pass 100% support (?). If this is the case then we cannot build/specify a conformance test suite based solely on this specification. We need some subset of functionality that all WAVE compliant devices are guaranteeing to support.

**Comment by mavgit** [comment]
One way to deal with this would be to pretest the test suite against releases of all four browser code bases that are contemporaneous with the API spec publication, then drop any test that fails on any of the code bases. This would result in a test suite that is known to run on any of the browser bases.

If the test suite later fails against a device, it would indicate that either:
- the device used an older browser release and should update to a more recent browser release, and/or
- there was some error in the integration process that should be fixed.

**Comment by andyburras** [comment]
Discussed on HATF call 2017-10-24.
Agreed that Mark's proposed approach (above) would be adopted.
There is a decision to take as to on what actual date to "snapshot" the stable browser versions, prior to doing the "test-run and identify" exercise.
So I think this issue ican be closed.
