### ISSUE TITLE
Editor's Note on WebDriver should be removed once test approach is clear

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#118]
The following note remains in the current version of the specification:

>EDITOR'S NOTE
>
>WebDriver API is at risk of removal from this specification pending resolution of https://github.com/w3c/webdriver/issues/977

The referenced issue has been resolved - it was closed with no change - so this note appears redundant.

Presumably the concern which led to this note being added still exists. Are we going to remove the specification or remove/reword the note?

**Comment by davemevans** [comment]
Discussed on telco 01/11/17: 
This is no longer pending on the specific issue, but on a larger question around our test approach. See related thread: https://lists.w3.org/Archives/Public/public-web-and-tv/2017Oct/0014.html

Consensus reached to change the note to mention this wider question rather than a specific closed issue.

**Comment by davemevans** [comment]
Original issue addressed via https://github.com/w3c/webmediaapi/commit/cb04c5c9d8601c6e35fe081b2afa2bbe88381c9c.

Will edit title and leave this issue open for further discussion as our test approach becomes clearer.

**Comment by mavgit** [comment]
Consensus on November 27, 2017 TWG call to remove the Webdriver API requirement and associated editor's note from the spec. After this edit, this version will be submitted for final publication on the CG site.

Editors: Please remove the Webdriver API requirement bullet and the associated editor's note from section 3.9.
