### ISSUE TITLE
CSSOM View Module

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#12]
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;
[CSSOM-VIEW]
Anne van Kesteren. CSSOM View Module. 4 August 2011. W3C Working Draft. URL: http://www.w3.org/TR/2011/WD-cssom-view-20110804

**Comment by jpiesing** [comment]
The requirement in OIPF inherited by HbbTV was the following;

> Terminals SHALL support innerWidth and innerHeight properties of the Window interface as defined in [CSSOM-VIEW]. Terminals SHOULD support other features defined in [CSSOM-VIEW].
> 
> Many of the features included in CSSOM-VIEW have been supported in browsers for a long time. For example, the Screen interface or extensions to the Window interface to obtain the width of the viewport through script. Future versions of this profile may mandate support for this specification, once it reaches a higher level of maturity.

This was based on specific video app provider requirements for innerWidth and innerHeight but the spec also containing things that were very immature.

**Comment by mavgit** [comment]
HTML 5 includes a [Normative reference](https://www.w3.org/TR/html5/references.html#references) as [CSSOMVIEW] to this later version of the spec:

>CSSOM View Module (URL: http://dev.w3.org/csswg/cssom-view/), S. Pieters, G. Adams. W3C.

HTML 5.1 includes a [Normative reference](https://www.w3.org/TR/html51/references.html#normative) as [CSSOM-VIEW] to this still later version of the spec:

>Simon Pieters. CSSOM View Module. 17 March 2016. WD. URL: https://www.w3.org/TR/cssom-view-1/

Since the Web Media API spec references HTML 5.1, I suggest we don't need to add a third variant of this reference, particularly one five years older.

**Comment by jpiesing** [comment]
@mavgit "Since the Web Media API spec references HTML 5.1, I suggest we don't need to add a third variant of this reference, particularly one five years older." That was never the proposal so I agree with you 100%.

I've reviewed the use of the [CSSOM-VIEW] reference in HTML5.1. It also subsets this specification. It does not obviously refer to innerHeight and innerWidth which were the reasons for HbbTV including this. Of course things may have moved on but it should be a conscious decision not to include these and not something that just happens accidentally.

**Comment by mavgit** [comment]
@jpiesing wrote:

>I've reviewed the use of the [CSSOM-VIEW] reference in HTML5.1. It also subsets this specification. It does not obviously refer to innerHeight and innerWidth which were the reasons for HbbTV including this.

First, the HTML 5.1 referenced spec of [CSSOM-VIEW] still includes [innerHeight and innerWidth](https://www.w3.org/TR/cssom-view-1/#extensions-to-the-window-interface) as extensions to the Window interface. (John, I think you know this, but FYI for others.)

Second, I didn't read any part of HTML 5.1 as subsetting [CSSOM-VIEW]. I do see that HTML 5.1 mentions many parts of [CSSOM-VIEW] and doesn't mention innerHeight or innerWidth specifically, but I don't read that as a subsetting. However, it would be best to ask the editors of their intention, so I'll send an email.

**Comment by jpiesing** [comment]
@mavgit If I look at where [CSSOM-VIEW] is used in HTML51,  see the following;
1) Section 1.8
> Other features in the platform can be used for the same purpose, though, including, though not limited to:
>     The exact list of which features a user agents supports.
>     The maximum allowed stack depth for recursion in script.
>     Features that describe the user’s environment, like Media Queries and the Screen object. [MEDIAQ] [CSSOM-VIEW]
>     The user’s time zone.
>

2) In section 2.2.2 where it says the following;

> Implementations that support scripting must support the CSS Object Model. The following features and terms are defined in the CSSOM specifications: [CSSOM] [CSSOM-VIEW]
>     Screen
>     LinkStyle
>     CSSStyleDeclaration
>     cssText attribute of CSSStyleDeclaration
>     StyleSheet
>     create a CSS style sheet
>     remove a CSS style sheet
>     associated CSS style sheet
>     CSS style sheets and their properties: type, location, parent CSS style sheet, owner node, owner CSS rule, media, title, alternate flag, disabled flag, CSS rules, origin-clean flag
>     Alternative style sheet sets and the preferred style sheet set
>     Serializing a CSS value
>     run the resize steps
>     run the scroll steps
>     evaluate media queries and report changes
>     Scroll an element into view
>     Scroll to the beginning of the document
>     The resize event
>     The scroll event
>     The features argument of window.open

You'll note that innerWidth and innerHeight aren't mentioned here. Neither is "extensions to the window interface" which is the section of CSSOM-VIEW that includes them.

This looks like it's defining a subset to me.

3)
> Interpret features as defined in the CSSOM View specification. [CSSOM-VIEW]
4)
> If target is the top of the document, then scroll to the beginning of the document for the Document, and abort these steps. [CSSOM-VIEW]
>Use the scroll an element into view algorithm to scroll target into view, with the align to top flag set. [CSSOM-VIEW]
5)

> For each fully active Document in docs, run the resize steps for that Document, passing in now as the timestamp. [CSSOM-VIEW]
> For each fully active Document in docs, run the scroll steps for that Document, passing in now as the timestamp. [CSSOM-VIEW]
> For each fully active Document in docs, evaluate media queries and report changes for that Document, passing in now as the timestamp. [CSSOM-VIEW]
6) 
> [CSSOM-VIEW] defines the following terms:
>     evaluate media queries and report changes
>     resize
>     run the resize steps
>     run the scroll steps
>     scroll
>     the features argument of window.open 
7)

>  [CSSOM-VIEW] defines the following terms:
>     Screen
>     clientY
>     screenX
>     screenY
>     scroll an element into view
>     scroll to the beginning of the document

**Comment by mavgit** [comment]
I read all that. To me, listing an incomplete set of terms doesn't imply that the spec is being subsetted without some explicit language of subsetting.  However, I sent an email to ask the editors, so we'll see.

**Comment by davemevans** [comment]
@mavgit did you get a response to your email to the editors?

I don't agree that listing terms from that spec which are used explicitly in HTML5.1 algorithms is subsetting, but merely ensuring that the sourcing of those terms is clear.

It seems to me that, since HTML5.1 normatively references CSSOM-VIEW and says "Implementations that support scripting must support the CSS Object Model", no action is needed here.

**Comment by davemevans** [comment]
Travis' response:

>>My view:
> 1. Does HTML 5.1 subset [CSSOM-VIEW] or include the whole spec?
>>It is not a goal for HTML to subset CSSOM-VIEW in any way. There may be a lot of cross-referencing of necessity, but there is no intention to integrate that spec.
> 2. Specifically, does HTML 5.1 include innerHeight and innerWidth?
>>I don’t see these defined in our editor’s draft…nor in the WHATWG html spec.

There was no objection on 22/03/17 telco to close with no further action.
