### ISSUE TITLE
How should we specify WebGL in the spec?

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#122]
I just noticed a small error in the API spec that was recently approved for publication: WebGL, one of the Section 4 APIs "proposed to be supported on all platforms", is already supported on all four target code bases since before the mid-2017 spec target date!

WebGl was included as a proposed API in the first draft of the spec in late 2016, because it wasn't implemented at the time by Microsoft Edge. However, Microsoft Edge implemented WebGL in Spring of 2017, well before the mid-2017 spec target. Unfortunately, I only just noticed this!

Since WebGL is supported in all four target code bases, it doesn't fit the section description that it is "not yet implemented widely enough to be Required." More importantly, it makes this spec look a bit silly to be asking that WebGL "be implemented on all HTML user agents as soon as possible", since it already is!

I propose we simply delete WebGL from this section 4, which means deleting section 4.3, since WebGL is the only graphics spec:

> 4.3 Graphics specifications
> - WebGL Specification, Version 1.0.3 [WEBGL]

Note 1: I don't think WebGL should be added to Section 3.5, because while WebGL is supported in all code bases, it won't necessarily be implemented by all devices due to hardware requirements. This is similar to our decision on issue #110 on the Geolocation API, which is also implemented in all code bases, but not on all devices, due to hardware requirements.

Note 2: I analyzed all the other Section 4 Proposed APIs and none of the others are fully supported by all four browser code bases, so this problem is unique to WebGL. (See attached PDF.)

[WebMediaAPIProposedAPISupport.xlsx.pdf](https://github.com/w3c/webmediaapi/files/1550019/WebMediaAPIProposedAPISupport.xlsx.pdf)

**Comment by wilaw** [comment]
@mavgit  – this appears to be a contradiction. You first say that “_Since WebGL is supported in all four target code bases, it doesn't fit the section description that it is ‘not yet implemented widely enough to be Required.’_” and then say “ . _while WebGL is supported in all code bases, it won't necessarily be implemented by all devices due to hardware requirements._”. Since it is not implemented on devices, doesn’t that mean that the original condition for Section 4 inclusion still stands i.e ‘not yet implemented widely enough to be Required’ ? 

To me, in any practical interpretation, “support” implies implementation. If we remove WebGL from Section 4 but don’t add it to 3.5, then it sits in API no-man’s land. 

Would it better to leave WebGL as it is (a desirable feature we hope will be widely available on all devices) and simply amend the definition of section 4 to be "proposed to be _implemented_ on all platforms"?

Cheers
Will

**Comment by jpiesing** [comment]
I think this is a disconnect between the actual criteria used for inclusion in section 4 and what is written in the document. As @mavgit says, the actual criteria is support in all 4 target code bases and WebGL meets this. However what is written in the document is not the same - "APIs in this section represent desired functionality that is important for web media delivery, but is not yet implemented widely enough to be Required." Many media devices may not have sufficient 3D graphics hardware acceleration for WebGL so WebGL may not meet the criteria as written.

**Comment by davemevans** [comment]
Anecdotally, there are mid-range devices without complete enough acceleration for WebGL and insufficient CPU for a performant software implementation.

There appear to be at least five options on the table:

* Remove WebGL completely as proposed in https://github.com/w3c/webmediaapi/issues/122#issue-281233474, possibly with a note mentioning performant hardware is required.
* Move WebGL to Section 3, test the API surface in our tests and leave DPCTF to do performance testing
* Move WebGL to Section 3, test the API surface in our tests, and add a note stating that devices without hardware/ CPU support may choose not to support this.
* Add another non-normative section (or split section 4) with items requiring performant hardware, noting that we wish to see this in the future.
* Leave it where it is, with a note encouraging hardware integration

(Note: all but the first option require more than editorial changes, and the spec has already approved, which may require re-approval)

(Note: all but the first option would probably mean we need to re-evaluate Geolocation, and probably other APIs)

ACTION: we should open an issue to start thinking about 2018 issues.

CONSENSUS: add a non-normative note to the existing WebGL entry stating something along the lines of "While webgl is supported in all code bases, we recommend that devices with performant hardware implement the spec."

**Comment by mavgit** [comment]
Reopen for reconsideration of how to handle WebGL for 2018 spec.

**Comment by mavgit** [comment]
At the 2018-09-18 WAVE face-to-face meeting in Amsterdam, there was consensus to move WebGL into section 3 (“Web Media APIs currently supported on all platforms”) of WMAS2018.

**Comment by mavgit** [comment]
[WebGL 1.0.3](https://www.khronos.org/registry/webgl/specs/1.0.3/) is [supported by all four code bases](https://caniuse.com/#feat=webgl).
[WebGL 2.0](https://www.khronos.org/registry/webgl/specs/latest/2.0/) (based on [OpenGL ES 3.0](https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf)) is [supported only on Chrome & Firefox at this time](https://www.khronos.org/registry/webgl/specs/latest/2.0/).
Therefore, WebGL 1.0.3 is our only option at this time.

**Comment by mavgit** [comment]
On the 2018-10-03 WAVE call, there was consensus to apply this pull request and there have been no dissenting comments on the issue since the call for consensus was posted two weeks earlier, so in accordance with our practice, I'm applying the pull request and closing the issue.
