### ISSUE TITLE
DOM level 3 events

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#13]
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;

[DOM-LEVEL-3-EVENTS-20120906]
Travis Leithead; Jacob Rossi et al. Document Object Model (DOM) Level 3 Events. 06 September 2012. Working Draft. URL: http://www.w3.org/TR/2012/WD-DOM-Level-3-Events-20120906/

**Comment by jpiesing** [comment]
The latest stable version of this redirects to UI Events - W3C Working Draft, 04 August 2016.
This is referenced from DOM4 which is referenced from the Web Media API spec. The following text from DOM4 suggests that UI Events is partly but not completed replaced by DOM4.
> By consolidating DOM Level 3 Core [DOM3CORE], Element Traversal [ELEMENTTRAVERSAL], Selectors API Level 2 [SELECTORSAPI], the "DOM Event Architecture" and "Basic Event Interfaces" chapters of UI Events [UIEVENTS] (specific type of events do not belong in the DOM Standard), and DOM Level 2 Traversal and Range [DOM2TR], and:

**Comment by jpiesing** [comment]
The requirement in OIPF is

>In addition to the support for the DOM 3 events specification that is required by HTML5 [HTML5-20130806], terminals SHALL support the focus and keyboard event types defined in section 5.2.2 and 5.2.5 respectively of [DOM-LEVEL-3-EVENTS-20120906].

and

>In order to support legacy content, Terminals SHALL support also the legacy attributes keyCode and charCode as defined in Appendix B of [DOM-LEVEL-3-EVENTS-20120906].

`

**Comment by jpiesing** [comment]
See also #3 .

**Comment by mavgit** [comment]
@jpiesing I don't understand from above what is your specific issue or suggested change.

I think we need to assume the current W3C DOM document structure as our baseline and not try to recreate the 2012 version of DOM3 Events, which was significantly restructured.

Here's how those references stand now, specifically relating to key events, which seems to be at least part of the issue above.

- Web Media API references:
   - [HTML 5.1](https://www.w3.org/TR/html51/), which references:
      - [DOM](https://www.w3.org/TR/dom/), which references:
         - [UI Events](https://www.w3.org/TR/uievents/), which references both:
            - [UI Events KeyboardEvent code Values](https://www.w3.org/TR/uievents-code/) and
            - [UI Events KeyboardEvent key Values](https://www.w3.org/TR/uievents-key/).

This seems to cover DOM keyboard events well. Given this as our baseline, are there any issues?

**Comment by jpiesing** [comment]
@mavgit " I don't understand from above what is your specific issue or suggested change."

I just created issues for all the normative references in the HbbTV/OIPF WSTVP that were not in the current draft for this group. The only issue was to ensure that the differences were discussed. There is no suggested change.

**Comment by mavgit** [comment]
@jpiesing said
> There is no suggested change.

So, if there's no suggested change, can we close this issue?

**Comment by davemevans** [comment]
**Call for consensus**: Close issue with no action given discussion above.

**Comment by davemevans** [comment]
Consensus reached on telco 8/3/17.
