### ISSUE TITLE
WebGL version inconsistency

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#131]
Our reference to WebGL is this;
> [WEBGL]
> WebGL 2.0 Specification. Dean Jackson; Jeff Gilbert. Khronos. 12 August 2017. URL: https://www.khronos.org/registry/webgl/specs/latest/2.0/ 

Where it's used, we say this;
> WebGL Specification, Version 1.0.3 [WEBGL]

@mavgit Do we intend to reference 2.0 or 1.0.3?

**Comment by davemevans** [comment]
Looks like the reference has moved from underneath us ([WEBGL] is just an alias), and we probably intended to point to 1.0.3, but will let @mavgit have his say (and other of course :wink:)

Note: there is currently no specref entry for 1.0.3 (which isn't a problem, they can be added very quickly) - [WEBGL-1] points at latest.

**Comment by mavgit** [comment]
Agree that it looks like SpecRef changed the reference underneath us. (We may want to avoid putting the version number in our text and leave that for the reference section.)

As far as version, caniuse shows insufficient support for WebGL 2: https://caniuse.com/#search=webgl%202

...so I guess we should add a 1.0.3 reference to SpecRef and use that.

**Comment by davemevans** [comment]
Consensus reached on 07/02/18 call to add WEBGL 1.0.3 to specref and update the reference in the spec to point to that.

**Comment by davemevans** [comment]
https://github.com/tobie/specref/pull/434 for the specref change.
