### ISSUE TITLE
Should Web Media API Snapshot 2018 be released on July 1, 2018 or another date? 

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#132]
Should Web API Snapshot 2018 2018 be released on July 1, 2018 or another date? 

There's been some discussion of releasing Web Media Application Developer Guidelines 2018 in the Fall or Spring to coincide with Safari & Edge major feature releases.

What works for manufacturers and other parties?

Let's consider just 3 quarterly dates:

- April 1
- July 1
- October 1

**Comment by davemevans** [comment]
~Should this issue be raised under https://github.com/w3c/webmediaguidelines/issues?~

(Fixed by editing the title)

**Comment by andyburras** [comment]
With regard to testing, there is an RfP currently out which covers the 2017 specification. Closing date for submissions is end Feb. If there was a 2018 spec in the first part of the year then this would probably be out before the 2017 test were completed.

**Comment by jpiesing** [comment]
As requested, here is the comment I made in the call today.
IMHO a new version so soon after the first version is at best irrelevant as device manufacturers will need to catch up with the first version.
A new version so soon after the last one will also go down badly with some & will be seen as indicating a lack of understanding of the needs of the CE device business.
Apart from fixing bugs, we might consider skipping 2018 all together.

**Comment by mavgit** [comment]
Comment from Ken Lowe:

For majors changes to product manufacturers need to know these changes by Q2 so that the product can be modified and fully tested before the new year.   Production has to commence at the start of the year to fill the supply line and stores as the retailers change their store assortment in the April/May timeframe.

**Comment by mavgit** [comment]
Consensus from the call was to plan for a annual specification update in Q4, starting with Q4 2018.
