### ISSUE TITLE
Which Progressive Web App specs should be added?

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#139]
There seemed to be consensus last year that the Progressive Web App (PWA) model should be supported, but it was excluded from WMAS2017 because none of the APIs were supported on all four code bases.

Issue #69 identified 2 required APIs:
- [Web App Manifest, WD, 04 September 2018](https://www.w3.org/TR/appmanifest/)
- [Service Workers Nightly, ED, 26 August 2018](https://w3c.github.io/ServiceWorker/)

and 3 recommended, but optional, APIs:
- [Background Fetch, ED, 21 August 2018](https://wicg.github.io/background-fetch/)
- [Media Session Standard, ED, 17 August 2017](https://wicg.github.io/mediasession/)
- [Web Notifications, REC, 22 October 2015](https://www.w3.org/TR/notifications/)

**Publication Status:** Only Web Notifications is a REC (W3C Recommendation). The others are ED (Editor's Draft) or WD (Working Draft).

**Implementation status:** [caniuse.com](caniuse.com) shows the following browser support:
Required APIs:
- [Web App Manifest](https://caniuse.com/#search=web%20app%20manifest) 1 code base, 1 partial
- [Service Workers](https://caniuse.com/#search=service%20workers) All 4 code bases.

Optional APIs:
- Background Fetch, (Not included in caniuse) 
- Media Session, (Not included in caniuse)
- [Web Notifications, REC, 22 October 2015](https://caniuse.com/#search=web%20notifications)  All 4 code bases.

Some questions:

1. If both Web App Manifest and Service Workers are required for PWAs, but only Service Workers is fully supported, can PWAs be supported across code bases today?

2. Does anyone know the implementation status of Background Fetch and Media Session?

3. Does it make sense to add support for the widely supported Service Workers and Web Notifications specs, regardless of the overall PWA support?

**Comment by jpiesing** [comment]
> Does it make sense to add support for the widely supported Service Workers and Web Notifications specs, regardless of the overall PWA support?

Web Notifications has integration issues regardless of support in the browser code base. I don't know how media devices would support notifications.

**Comment by mavgit** [comment]
Web Notifications is already in the 2017 spec in [3.9 Other web specifications](https://www.w3.org/2017/12/webmediaapi.html#other-web-specifications).

So, I'd restate my previous questions as:
1. If both Web App Manifest and Service Workers are required for PWAs, but only Service Workers is fully supported, can PWAs be supported across code bases today?
2. Does anyone know the implementation status of Background Fetch and Media Session?
3. Does it make sense to add support for the [widely supported Service Workers spec](https://caniuse.com/#search=service%20workers), regardless of the overall PWA support?

**Comment by mavgit** [comment]
At the 2018-09-18 WAVE face-to-face meeting in Amsterdam, there was consensus to add Service Workers to Section 3 APIs.

**Comment by mavgit** [comment]
On the 2018-10-03 WAVE call, there was consensus to apply this pull request and there have been no dissenting comments on the issue since the call for consensus was posted two weeks earlier, so in accordance with our practice, I'm applying the pull request and closing the issue.
