### ISSUE TITLE
Media Fragments URI

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#14]
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;

[MEDIA-FRAGS-20120925]
Raphaël Troncy et al. Media Fragments URI 1.0 (basic). 25 September 2012. W3C Recommendation. URL: http://www.w3.org/TR/2012/REC-media-frags-20120925/

**Comment by jpiesing** [comment]
This spec is used as follows;

> Whenever an application points to a media resource through a URI (e.g. via the src attribute of the <video> element), it MAY include a Fragment Identifier [RFC3986]. The semantics of such fragments for resources of type audio/*, image/* and video/* are defined in [MEDIA-FRAGS-20120925].
Terminals SHALL support temporal clipping based on Normal Play Time as defined in section 4.2.1 of the Media Fragments URI specification [MEDIA-FRAGS-20120925].
NOTE
There is no requirement to support other means of specifying temporal clipping mentioned in that document such as SMPTE timecodes or real-world clock time or to support the URI query mechanism.

temporal clipping provides a way to play from one a begin time to an end time, e.g. to stop playing a content item at an ad break.

Media Fragments is a normative reference from HTML5.1 but only very specific features are referenced. The begin time is sort-of referenced but end time may not be.

> If either the media resource or the address of the current media resource indicate a particular start time, then set the initial playback position to that time and, if jumped is still false, seek to that time and let jumped be true.
> EXAMPLE 83
> For example, with media formats that support the Media Fragments URI fragment identifier syntax, the fragment identifier can be used to indicate a start position. [MEDIA-FRAGS]

**Comment by mavgit** [comment]
Is there any data on current browser support for the Media Fragments URI spec?

I note that there was a 2015 feature suggestion to caniuse.com to [track Media Fragments URI support](https://github.com/Fyrd/caniuse/issues/1127) which currently stands at number 13 on the [suggestion list](http://caniuse.com/issue-list).

**Comment by jpiesing** [comment]
@mavgit > Is there any data on current browser support for the Media Fragments URI spec?

This is subset by HTML5. Since the subset survived the transition from HTML5 to HTML5.1, I'd hope this means the subset is implemented.

**Comment by davemevans** [comment]
HTML5.1 references the basic version of Media Fragments URI, which only defines temporal and spacial dimensions, but HTML5.1 mainly mentions the id dimension which is in the unreferenced, working draft, advanced version. As @jpiesing points out, there is an example that mentions the start time, but I am not sure this is truly a reference.

https://simpl.info/mediafragments/ has a very basic test of the temporal dimension which Chrome and Firefox pass - I don't have access to the other engines to test.

This seems like it would be a nice feature to have but we will need more comprehensive data on support.

**Comment by mavgit** [comment]
FWIW, OS X Safari Version 10.0.3 (12602.4.8) also seemed to pass the simple test at https://simpl.info/mediafragments/

**Comment by mavgit** [comment]
Current iOS Safari also seems to pass this simple test.

**Comment by davemevans** [comment]
I just tested the above example in Edge and found that it doesn't work.

**Comment by mavgit** [comment]
Given that we don't have even basic support for this spec across all four code bases, I propose we do not add this API to the 2017 spec and reexamine support for a future version. I propose closing this issue.

**Comment by mavgit** [comment]
The consensus seems to be to add a dated reference to this spec which is currently in WHATWG. The editors are currently investigating the best way to provide this reference.

**Comment by jpiesing** [comment]
@mavgit: Can you be specific about where this is in WHATWG? 

If you look around https://html.spec.whatwg.org/multipage/embedded-content.html#offsets-into-the-media-resource , references to media fragments are all to the 2012 W3C Recommendation.

**Comment by mavgit** [comment]
Sorry. WHATWG label applied in editing error. Removed.

**Comment by davemevans** [comment]
*Call for consensus:* Recommend https://www.w3.org/TR/media-frags/ since support is not complete across all engines.
