### ISSUE TITLE
Update old Web Socket, Web Workers, Web Storage & Web Notifications references to WHATWG

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#142]
Our 2017 spec references The WebSocket API [WEBSOCKETS], which points to a 2012 W3C spec:

>The WebSocket API. Ian Hickson. W3C. 20 September 2012. W3C Candidate Recommendation. URL: https://www.w3.org/TR/websockets/

This spec has a big banner across the top:
> Document Status Update 2015-10-24: This paragraph is informative. The URL of the latest Editor's Draft has been modified. Please look at http://w3c.github.io/websockets/ for the latest changes.

this then points to:
>No one in the Web Platform Working Group is actively working on this specification. For the latest version of The WebSocket API use the [WHATWG Living Standard](https://html.spec.whatwg.org/multipage/comms.html#network).

Given that we're pointing to a very old spec, I think we'd be better off pointing to the [WHATWG Web Sockets spec](https://html.spec.whatwg.org/multipage/comms.html#network), which is more up to date.

Note that the SpecRef reference database is currently missing a reference to the WHATWG Web Sockets spec, so I opened an issue on this: https://github.com/tobie/specref/issues/477

Note also that this will have no effect on our WAVE test suite, since the W3C WPT tests, which our test suite is based on, is used for testing both W3C and WHATWG specs.

**Comment by mavgit** [comment]
>Note that the SpecRef reference database is currently missing a reference to the WHATWG Web Sockets spec, so I opened an issue on this: tobie/specref#477

We got the [reply](https://github.com/tobie/specref/issues/477#issuecomment-422162252): "It's in the Network section of the HTML spec itself, so just reference it as [HTML]."

[HTML] is the WHATWG HTML.

So, our Web Sockets reference depends on which HTML spec we reference (issue #138 ):
- If we use HTML 5.2, the Web Sockets reference would be to section 9.3 of [HTML].
- If we use WHATWG HTML, we delete the Web Sockets reference, because it's already in [HTML].

**Comment by mavgit** [comment]
There are three additional (four total) references to W3C specs that are really WHATWG specs:
- WebSocket API [WEBSOCKETS]
- Web Storage [WEBSTORAGE]
- Web Workers [WORKERS]
- Web Notifications [notifications-20151022]

**Comment by davemevans** [comment]
I think XHR also falls into the WHATWG category?

Also, Channel Messaging and Cross-document Messaging are in the WHATWG HTML spec (the spec links are currently defined in the `localBiblio` section), so these could also be removed with a move to the WHATWG HTML spec.

**Comment by mavgit** [comment]
@davemevans In the four specs  I mention in https://github.com/w3c/webmediaapi/issues/142#issuecomment-422213266, our Snapshot 2017 spec references an old abandoned W3C spec. In all four cases, the spec work is all in WHATWG and there is no work in W3C. Those could all be moved from old W3C reference to active WHATWG reference.

In the three specs you mention in https://github.com/w3c/webmediaapi/issues/142#issuecomment-422272013, our Snapshot 2017 spec already references the WHATWG spec, so no change is needed.

I updated the issue title to mention all 4 specs.

**Comment by davemevans** [comment]
Sorry, you are correct wrt XHR - I had forgotten all the discussion we had in #1.

My point (now clarified in the comment) with the other two was the same as yours in https://github.com/w3c/webmediaapi/issues/142#issuecomment-422176001 - if WHATWG HTML is referenced, those can be removed because they come for free in that spec. This would also remove the need for the `localBiblio` hack.

**Comment by mavgit** [comment]
@davemevans Agree. Getting rid of the `localBiblio` hack would be great!

**Comment by mavgit** [comment]
At the 2018-09-18 WAVE face-to-face meeting in Amsterdam, there was consensus that Web Socket, Web Workers, Web Storage, and Web Notifications references be updated to WHATWG specs.

**Comment by mavgit** [comment]
The W3C [Web Notifications](https://www.w3.org/TR/notifications/) spec could be updated to the WHATWG [Notifications API](https://notifications.spec.whatwg.org) spec.

Web Socket, Web Workers and Web Storage are different because they are not standalone WHATWG specs. They are all subsections of the [WHATWG HTML](https://html.spec.whatwg.org) spec. We have three choices:
1. Adopt the WHATWG HTML spec and delete the Web Socket, Web Workers and Web Storage references.
2. Adopt HTML 5.2 and additionally reference three chapters of the WHATWG HTML spec.
3. Continue to reference the old W3C Web Socket, Web Workers and Web Storage specs.

**Comment by mavgit** [comment]
As a first step, call for consensus to change from W3C [Web Notifications](https://www.w3.org/TR/notifications/) spec to the WHATWG [Notifications API](https://notifications.spec.whatwg.org) spec.

**Comment by mavgit** [comment]
On the 2018-09-17 HATF call, there was consensus to:
1. change from W3C [Web Notifications](https://www.w3.org/TR/notifications/) spec to the WHATWG [Notifications API](https://notifications.spec.whatwg.org) spec (PR #155)
2. change Web Socket, Web Workers and Web Storage to reference the corresponding chapters of the [WHATWG HTML](https://html.spec.whatwg.org) spec (https://github.com/w3c/webmediaapi/issues/142#issuecomment-426546171, option 2) (new PR).

**Comment by mavgit** [comment]
Changed Web Socket, Web Workers and Web Storage to reference the corresponding chapters of the WHATWG HTML spec.
