### ISSUE TITLE
Add section to list dependent specs that we want to test

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#143]
When we sent the RFP for the Snapshot 2018 test suite, we added a few specs that we wanted to include in the test suite that aren't in the Snapshot 2017 spec because they're already referenced by other Snapshot 2017 specs. For 2017, the list was:
- [UI Events](https://www.w3.org/TR/uievents/)
- [Web Sockets](https://html.spec.whatwg.org/multipage/web-sockets.html#network) 
- [Cssom-view](https://www.w3.org/TR/cssom-view-1/)	
- [DOM4](https://www.w3.org/TR/dom/)

I'd like to add a section to the Snapshot 2018 spec which includes all additional specs for testing, so we have all the specs to be tested in one public spec.

**Comment by jpiesing** [comment]
We should also consider adding the File API as some things in that API are used by media apps such as createObjectURL.

**Comment by mavgit** [comment]
At the 2018-09-18 WAVE face-to-face meeting in Amsterdam, there was consensus to add dependent specs that we want to test to Section 3 APIs.

We'll immediately add the specs already added to the 2017 tests:
- UI Events
- Cssom-view
- DOM4

(Note that Web Sockets, listed in https://github.com/w3c/webmediaapi/issues/143#issue-361165587, is already included in Section 3.

**Comment by mavgit** [comment]
On the 2018-10-03 WAVE call, there was consensus to apply this pull request and there have been no dissenting comments on the issue since the call for consensus was posted two weeks earlier, so in accordance with our practice, I'm applying the pull request and closing the issue.

**Comment by jpiesing** [comment]
I only just noticed that the pull request did not take account of my comment above that "We should also consider adding the File API as some things in that API are used by media apps such as createObjectURL.".

@mavgit Would you rather I re-open this issue or create a new one?

**Comment by mavgit** [comment]
I agree that File API should be added. I don't think it should be controversial. I'll follow whatever the Amsterdam meeting notes (which I can't find at the moment) say about the F2F consensus. If we need to open a new issue, it should just go through.

**Comment by mavgit** [comment]
On the 2018-09-17 HATF call, there was consensus to add File API to section 3 APIs.

**Comment by jpiesing** [comment]
Looking at caniuse.com, I see that Edge and IE have a note that " Does not support the File constructor".
We might want to call that out as one of the "Features with limited implementation".
Some other features had issues with IE but I didn't see anything else that had issues with Edge/Webkit/Chrome/Firefox.

**Comment by mavgit** [comment]
@jpiesing  said in https://github.com/w3c/webmediaapi/issues/143#issuecomment-430769077

> Looking at caniuse.com, I see that Edge and IE have a note that " Does not support the File constructor".
We might want to call that out as one of the "Features with limited implementation".

I agree. Good catch. We'll add an exception for File constructor.

**Comment by mavgit** [comment]
Added File API with exception for File constructor.
