### ISSUE TITLE
Web Messaging

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#15]
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;
[POSTMSG-20120501]
Ian Hickson. HTML5 Web Messaging. 01 May 2012. W3C Candidate Recommendation. URL: http://www.w3.org/TR/2012/CR-webmessaging-20120501

**Comment by jpiesing** [comment]
This reached a Recommendation in 2015 (see https://www.w3.org/TR/webmessaging/ ) but now carries the following note:

>  No one in the Web Platform Working Group is actively working on the Web Messaging specification. For the latest version of the specification use the WHATWG Living Standard: Cross-document messaging and Channel messaging.

**Comment by mavgit** [comment]
Regardless of where the spec is now, what is the specific requirement in this area?

FYI, caniuse.com shows strong support for the two major features of this spec:
- [Channel messaging](http://caniuse.com/#search=channel%20messaging)
- [Cross-document messaging](http://caniuse.com/#search=cross-document)

**Comment by jpiesing** [comment]
@mavgit " what is the specific requirement in this area?
>FYI, caniuse.com shows strong support for the two major features of this spec:
>    Channel messaging
 >   Cross-document messaging"

The HbbTV requirement was both of these.

**Comment by mavgit** [comment]
The consensus seems to be to add a dated reference to this spec which is currently in WHATWG. The editors are currently investigating the best way to provide this reference.

**Comment by mavgit** [comment]
Call for Consensus:

The editors have not been able to come up with a workable way to create a dated reference to the WHATWG spec, as proposed above on March 6. Therefore, I propose a Call for Consensus for the editors to add undated references to the two WHATWG specs:
- Cross-document messaging, https://html.spec.whatwg.org/multipage/comms.html#web-messaging
- Channel messaging, https://html.spec.whatwg.org/multipage/comms.html#channel-messaging
(Note: These are the same references used by caniuse.)
These can be added to section 2.9, Other web specifications.

**Comment by jpiesing** [comment]
IMHO undated references to WHATWG specifications puts into question some of the intended uses for our specification. At the very least those uses would require a separate side-letter or contract specifying a WHATWG version no earlier than a certain date or including a certain feature.

**Comment by davemevans** [comment]
I created #75 to address the CfC even though we possibly don't have consensus since it contains undated references.

**Comment by davemevans** [comment]
Consensus reluctantly reached on 14/06/17 call since there doesn't seem to be a better way to reference WHATWG specs.
