### ISSUE TITLE
Websocket protocol - RFC6455

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#16]
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;

[RFC6455]
I. Fette; A. Melnikov. The WebSocket Protocol. December 2011 including verified errata. URL: http://tools.ietf.org/html/rfc6455

**Comment by davemevans** [comment]
Websockets is referenced, but it's the [W3C version](https://www.w3.org/TR/websockets/) as opposed to the RFC listed above. I don't know how those two documents are related.

**Comment by jpiesing** [comment]
This is in fact a different spec from the W3C one. The W3C spec defines the API and the RFC defines the protocol. The protocol was referenced in OIPF because the W3C spec didn't properly reference the protocol and historically had been used with other protocols.

**Comment by jpiesing** [comment]
Also the W3C spec only got as far as a Candidate Recommendation before development stopped only to continue in WHATWG. 
> No one in the Web Platform Working Group is actively working on this specification. For the latest version of The WebSocket API use the WHATWG Living Standard.

**Comment by mavgit** [comment]
The Web Media API spec references HTML 5.1, [which includes a normative reference to RFC 6455](https://www.w3.org/TR/html51/single-page.html#biblio-rfc6455):

> [RFC6455]
I. Fette; A. Melnikov. The WebSocket Protocol. December 2011. Proposed Standard. URL: https://tools.ietf.org/html/rfc6455

So, I think this issue can be closed.

**Comment by jpiesing** [comment]
@mavgit If you look at where that normative reference is used, it's used exactly once, in 2.2.2 where it introduces a long list of terms ("The following terms are defined in the WebSocket protocol specification: [RFC6455]"). See https://www.w3.org/TR/html51/single-page.html#establish-a-websocket-connection .
Unfortunately the only time those terms are used is in the index.

**Comment by mavgit** [comment]
I read that, but I still don't see the issue. The RFC is referenced normatively. Adding another reference in our doc to the same RFC adds nothing that I can see.

As a practical issue, is there some interoperability problem with current web clients wrt RFC455?

**Comment by jpiesing** [comment]
> I read that, but I still don't see the issue. The RFC is referenced normatively. Adding another reference in our doc to the same RFC adds nothing that I can see.

This may be a cultural issue but, for me, all that matters is the magic word "shall" (or "must" where allowed). A normative reference without "shall"s is meaningless.

**Comment by tidoust** [comment]
> This may be a cultural issue but, for me, all that matters is the magic word "shall" (or "must" where allowed). A normative reference without "shall"s is meaningless.

I agree with @jpiesing here. The meaning of "normative reference" can be fuzzy. Some specs appear as normative references, only because they define some useful terms. In such cases, it's not entirely clear whether there is a requirement to implement the spec as a whole. We need to pay attention to the normative vocabulary that creates the references each time. For instance, I noted in #3 that support for DOM4 and UI Events is explicitly required by HTML 5.1.

Now, the Web Socket API, which we require, builds on top of the Web Socket protocol, and there is no way to implement the Web Socket API without also supporting the Web Socket protocol, so I don't think the Web Media API spec needs to reference the Web Socket protocol RFC.

**Comment by jpiesing** [comment]
> Now, the Web Socket API, which we require, builds on top of the Web Socket protocol, and there is no way to implement the Web Socket API without also supporting the Web Socket protocol, so I don't think the Web Media API spec needs to reference the Web Socket protocol RFC.

@tidoust When the HbbTV/OIPF work started, RFC6455 was not published and what I remember is that implementations of the websocket API used semi-proprietary variations on the same theme. I know these will have vanished from the current codebase of the main browsers but will there still be old versions of those browsers floating around in TV platforms?

**Comment by tidoust** [comment]
@jpiesing There may still be old versions with semi-proprietary variations of the Web socket protocol, but as far as I can tell, they no longer qualify as valid implementations of the Web Socket API.

**Comment by mavgit** [comment]
Call for Consensus
Close issue with no action.

**Comment by joeyparrish** [comment]
I concur, we should close.

**Comment by davemevans** [comment]
Consensus reached on telco 03/05/17.
