### ISSUE TITLE
Guidance on cookie storage

### ISSUE THREAD

**Issue by johnluther** [w3c-cg/webmediaapi#168]
Related to issue #144 (and also w3c/webmediaporting/issues/6 in the deprecated porting spec repo), the HATF co-chairs propose to add guidance to the API spec regarding cookies. 

The proposal is to recommend that implementations support a minimum of 20 cookies per domain, 100 total and 4096 bytes per cookie (essentially, the Open IPTV Forum Web TV spec requirement). According to my research, all four major browser code bases will support this recommendation.

**Comment by mavgit** [comment]
That's now in draft section 4.1 of the spec.

**Comment by mavgit** [comment]
In the 2018-10-25 HATF call, there was consensus to include the cookie storage requirements and to fix the draft requirements:
- numerical requirements should state "at least", as in "Devices MUST support at least 100 total cookies."
- Persistence requirement should add persistence across power cycles of the device.

**Comment by mavgit** [comment]
Fixed requirements. Closing.
