### ISSUE TITLE
Guidance on Web Storage

### ISSUE THREAD

**Issue by johnluther** [w3c-cg/webmediaapi#169]
Related to issue #144, the HATF co-chairs propose to add guidance to the API spec regarding Web Storage. 

The proposal is to recommend a maximum of 5MB for LocalStorage and 5MB for SessionStorage. My research indicates that Edge, Chrome and FF support max of 10MB for each, but Safari only supports 5MB.

**Comment by mavgit** [comment]
That's now in draft section 4.2 of the spec.

**Comment by mavgit** [comment]
In the 2018-10-25 HATF call, there was consensus to include the LocalStorage and SessionStorage requirements and to fix the draft requirements to state "at least", as in "Devices MUST support LocalStorage of at least 5 MB..

**Comment by mavgit** [comment]
Added "at least" to storage requirements. Closing.
