### ISSUE TITLE
Changes to introductory text.

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#170]
I have updated the text in the following initial sections of the spec:
>Abstract
> 1. Introduction
> 1.1 Out-of-date browsers
> 1.2 Integration issues
> 2. Conformance
> 3. Web Media APIs currently supported on all platforms
> 3.1 Introduction

The changes reflect the addition of the integration tests as well as clarifying and simplifying text in several areas.

In addition to a Pull Request with the changes, I also attach a Word file with tracked changes of the same text, to make reviewing easier..
[WMAS2018text.docx](https://github.com/w3c/webmediaapi/files/2512528/WMAS2018text.docx)

**Comment by mavgit** [comment]
In the 2018-10-25 HATF call, there was consensus to make these changes to the text. Applied.

**Comment by andyburras** [comment]
A very, very minor observation and feel free to ignore. Introduction 1.2 says "_Note that these values are not mandated by any web standards_"... except of course we **are** mandating them as part of WMAS.
Maybe "_not mandated by any referenced web standards_"
