### ISSUE TITLE
Add recommendation for regular updates

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#172]
At the 2018-10-02 WAVE face-to-face meeting in Hollywood, there was consensus to recommend that implementations support the evergreen model and include it in the WMAS2018 spec.

**Comment by jpiesing** [comment]
TP Vision continues to have the opinion expressed in the 8th October meeting of the TWG recorded in the minutes as "It is likely that any such recommendation will be ignored by manufacturers. May be different for STB manufacturers which may have updates included/covered by contract."

**Comment by mavgit** [comment]
In the 2018-10-25 HATF call, there was consensus to add this update section.
