### ISSUE TITLE
WebAudio

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#18]
One of the web APIs in HbbTV that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;

[65] W3C Working Draft (10th October 2013): "Web Audio API".
https://www.w3.org/TR/webaudio/

**Comment by jpiesing** [comment]
HbbTV says the following about this spec.

> The following interfaces from the Web Audio API [65] shall be supported with the properties and methods listed for each:
> • AudioNode: connect,disconnect, context, numberOfInputs, numberOfOutputs, channelCount,
> channelCountMode, channelInterpretation
> • AudioBufferSourceNode: buffer, start, stop, onended
> • AudioContext: createBuffer, createBufferSource, destination, sampleRate, currentTime, decodeAudioData
> • AudioBuffer: length, sampleRate, duration, numberOfChannels
> • AudioDestinationNode: maxChannelCount

**Comment by mavgit** [comment]
caniuse.com shows [strong support for Web Audio across browsers including Edge, but not IE](http://caniuse.com/#search=web%20audio) with some issues:
- Safari does not appear to support createMediaElementSource
- Safari usage supported with prefix webkit
- Not all browsers with support for the Audio API also support media streams (e.g. microphone input). See the getUserMedia/Streams API data for support for that feature.

**Comment by jpiesing** [comment]
@mavgit HbbTV defines a subset of this API which is aligned with subsets supported by forks of browsers for TV to meet other market requirements. This subset does not include microphone input (etc).

**Comment by svgeesus** [comment]
I agree that it is odd that WebAudio API is not listed. There is generally good support in browsers and it is clearly a relevant, media-related spec. Happy to see that this issue is already open.

Would a PR to add it help?

**Comment by davemevans** [comment]
My feeling is that we ought to have WebAudio in the specification.

Points for discussion here/at a future call:
* If an API is only available with a prefix in a required engine, is that sufficient for us to require support?
* Should we make createMediaElementSource optional?
* Should we make the Media Capture and Streams stuff optional?

or should we just make WebAudio recommended?

**Comment by mavgit** [comment]
Call for consensus:
1. Require WebAudio, even though one browser is currently still using a prefix API.
2. Note which sub-features of WebAudio are not supported.

**Comment by davemevans** [comment]
FYI Just tested Safari 10.0 (12602.1.50.0.10) `createMediaElementSource` using https://mdn.github.io/webaudio-examples/media-source-buffer/ and it works great.
