### ISSUE TITLE
add PAGEVIS support

### ISSUE THREAD

**Issue by mikedo** [w3c-cg/webmediaapi#182]
During discussions in ATSC, it has become clear that notification of an app no longer being visible is important. WHATWG has a non-normative reference to this: https://www.w3.org/TR/page-visibility-2/ which is currently in PR stage at W3C. It has broad support at https://caniuse.com/#search=pagevis
We should consider adding this normatively.

**Comment by mavgit** [comment]
On the 2018-10-31 HATF call, there was consensus to support the ATSC request https://github.com/w3c/webmediaapi/issues/182#issue-376043275 and add a normative reference to [Page Visibility Level 2](https://www.w3.org/TR/page-visibility-2/) [PAGE-VISIBILITY-2] to Section 3, Web Media APIs currently supported on all platforms.

**Comment by mavgit** [comment]
Added Page Visibility Level 2 [PAGE-VISIBILITY-2] to Section 3.
