### ISSUE TITLE
Section 4.3 storage requirements unbounded and too high.

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#195]
The section 4.3 storage requirements are unbounded and too high.

In talking with consumer device makers, the section 4.3 storage requirements will overrun available device memory. An app set of 200 apps would require one gigabyte of permanent localStorage on each device. 

In addition, unlike the 4.2 cookie requirements which are limited to 100 total cookies, there is no upper limit to number of apps and therefore no upper limit to LocalStorage.

I also note that the [Vewd device requirements](https://developer.vewd.com/m/mobile.action#page/2031812/header/CertifyforDevices-3.12.5.Storage) have both LocalStorage and SessionStorage as SHOULD rather than MUST.

I suggest the requirements be deleted. 

I’d like to also hear from device makers on this.

**Comment by poolec** [comment]
If there is an issue with the storage requirement being unbounded, then it's reasonable to address that.  However, it doesn't change the need for the requirement in the first place which is to make sure that implementations have a useful amount of storage, i.e. that (a) enough storage is reserved for the purpose, and (b) that there aren't inappropriately low per-origin limits in place.  We should not delete these requirements.

How about something along the lines of:
Devices MUST support LocalStorage of at least 5 MB, provided that the total data stored by all apps across all origins does not exceed 30 MB.

This would ensure that implementations reserve an appropriate amount of storage.  Typically, there won't be a large number of applications in regular use on a particular device all using the maximum storage, but if there are, then performance may degrade on those devices.

**Comment by mavgit** [comment]
@poolec 
>If there is an issue with the storage requirement being unbounded, then it's reasonable to address that. 

I agree that it is reasonable to address this. I think we should do it. I'm suggesting we leave it out of the spec to be published in mid-December 2018, because we need to do more work to justify both the storage per app (I think 5 MB is too high) and the total storage (currently unlimited) and the new values need to be reviewed.

I'd like to know:
1. What are the per app storage limits and total storage limits on mobile browsers today?
2. What are the per app storage limits and total storage limits on TV browsers today?
3. What are the per app storage requirements of media web apps today on PC, mobile & TV?
4. Can the device LocalStorage be stored in the cloud or must it remain on the device?
5. How much total physical storage can TVs, STBs, game machines and other TV-connected devices support?

I think our final November 28 call is too late to introduce new values because they can't be reviewed by either HATF or TWG. So I suggest we leave LocalStorage and SessionStorage out of the mid-December version and keep working on them. We also have several other integration values to set. When we are confident about a set of these, we can publish any time - we don't have to wait till December 2019.

**Comment by mavgit** [comment]
In the 2018-11-28 HATF call, there was consensus to delete the storage requirements. Applied PR #196.
