### ISSUE TITLE
Require GIF graphics format

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#2]
We would like to see GIF89a [1] support required in section 2.5 the spec.

Whilst I am aware that you can do animation of static images using CSS or Canvas tricks, animated GIFs can be very useful and widely deployed and require no script.

I can create a PR if there is consensus this would be a useful graphics format.

[1] Graphics Interchange Format. 31 July 1990. URL: https://www.w3.org/Graphics/GIF/spec-gif89a.txt

**Comment by mavgit** [comment]
David: I support this. Leaving out GIF is an oversight. Please create a PR.

HATF: Any objections? If not, we'll apply the PR.

Thanks,
mav

**Comment by mavgit** [comment]
~~**Call for consensus:** Don't specify Level 1 for XHR support. #5 
Please comment if you disagree. Silence is taken as consent.
We'll apply changes after the upcoming F2F.~~

**Comment by jpiesing** [comment]
I think the wrong text was copy/pasted into the CFC in the previous comment.

**Comment by mavgit** [comment]
@jpiesing Thanks! :blush:

**Call for consensus:** Fix #2: Add GIF89a to required graphics specifications
Please comment if you disagree. Silence is taken as consent.
We'll apply changes after the upcoming F2F.

**Comment by poolec** [comment]
Face to face 15/12/2016:
Concerns from some participants if people think animated GIFs are suitable for large or long duration animations, essentially standing in for video.
Agreed to add GIF89a but also add a note to state that the intended use is for UI features and not for video.

**Comment by davemevans** [comment]
Do we think that such a note belongs in the API list?
Would it be better in the app developer guidelines?

**Comment by davemevans** [comment]
<b>Call for consensus:</b> Merge PR #5, without a note in the API list
Please comment, preferably with proposed text, if you disagree. Silence is taken as consent.
We'll apply changes after the telco tomorrow.

**Comment by mavgit** [comment]
I agree with adding the GIF reference without the application note as proposed.

**Comment by davemevans** [comment]
22/02: Consensus reached on telco.
