### ISSUE TITLE
Which version of ECMAScript should be referenced?

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#20]
The Web Media API spec currently references:
>ECMAScript Language Specification, Edition 5.1 [[ECMASCRIPT-5.1]](http://www.ecma-international.org/publications/standards/Ecma-262.htm)

(Note that the link from www.specref.org erroneously links to the latest ECMAScript version, currently ECMAScript 7, not to ECMAScript 5.1!)

ECMA subsequently published:
- ECMAScript 6 [[ECMASCRIPT-6.0]](http://www.ecma-international.org/ecma-262/6.0/index.html) in 2015
- ECMAScript 7 [[ECMASCRIPT]](https://tc39.github.io/ecma262/) in 2016

I note that [HTML 5.1 references [ECMA-262]](https://www.w3.org/TR/html51/single-page.html#biblio-ecma-262).

I suggest:

1. Removing the Editor's Note on this matter from section 2.1, which is replaced by this Issue #20.

2. Removing any ECMAScript reference from section 2.1 and defer to the HTML 5.1 reference, to avoid any conflict or confusion.

**Comment by davemevans** [comment]
I have implemented (1) - see PR #36.

The problem with (2) is going to be the same problem we see in a number of places - the HTML5.1 reference is to a living standard which is going to make compliance testing impossible.

Modern browser support for ES6 seems [pretty good](http://kangax.github.io/compat-table/es6/) (although AFAIK no browser currently supports module importing), so that could be an option. Newer version seem to be poorly implemented (see other tabs of same table).

There are a number transpiling options which give developers access to all modern ES6 features and only require ES5 to be supported natively.

To be discussed on the next call.

**Comment by davemevans** [comment]
#36 will be merged after the call tomorrow since it is purely editorial.

Could CG members, particularly those with dev teams, and also those who would not want to defer to HTML5.1 provide input on this issue, so we can reach consensus.

**Comment by mavgit** [comment]
@bbcrddave wrote:
> The problem with (2) is going to be the same problem we see in a number of places - the HTML5.1 reference is to a living standard which is going to make compliance testing impossible.

I think this is conflating two issues, an HTML5.1 issue and an issue with our spec:

1. **HTML5.1 issue:** Your stated issue that "the HTML5.1 reference is to a living standard" is an issue on the HTML5.1 spec and the only way to address that is to open an issue against the HTML5.1 spec. There is nothing we can do in our spec to solve an issue with the HTML5.1 spec.

2. **Issue with our spec:** (2) just says to remove our duplicate reference to ECMAScript from our own spec, since our already-referenced HTML5.1 spec includes an ECMAScript reference. This is fully justified to avoid conflict and/or confusion.

So, I still support: "(2) Removing any ECMAScript reference from section 2.1 and defer to the HTML 5.1 reference, to avoid any conflict or confusion."

> Could CG members, particularly those with dev teams, and also those who would not want to defer to HTML5.1 provide input on this issue, so we can reach consensus.

I spoke with our developers and the ECMAScript versions are not an issue given the efficacy of implementing ECMAScript 6 features like promises on top of ECMAScript 5.

**Comment by jpiesing** [comment]
> Could CG members, particularly those with dev teams, and also those who would not want to defer to HTML5.1 provide input on this issue, so we can reach consensus.

For a device maker who wants to use the WAVE HTML5 spec in negotiations with a supplier, living standards without a date make it not fit for purpose. Without a specific reference as a minimum baseline, I have nothing to use when the supplier says that any version will do as nobody will have the latest version.

**Comment by mavgit** [comment]
Call for consensus to:
1. Require ECMAScript 5.1
2. Recommend ECMAScript 6
