### ISSUE TITLE
Update to CSS Snapshot 2018

### ISSUE THREAD

**Issue by JohnRiv** [w3c-cg/webmediaapi#202]
We currently reference **[CSS Snapshot 2017](https://www.w3.org/TR/css-2017/)**. Propose updating to **[CSS Snapshot 2018](https://www.w3.org/TR/css-2018/)**. Besides the list of specifications it covers (which I will create separate issues for each), the update from 2017 to 2018 appears to involve the following:

- [2.2. CSS Profiles](https://www.w3.org/TR/css-2018/#profiles) have been discontinued. In [2017](https://www.w3.org/TR/css-2017/#profiles) this mentioned items such as the `CSS TV Profile` that are no longer supported
- Addition of the new [4. Safe to Release pre-CR Exceptions](https://www.w3.org/TR/css-2018/#CR-exceptions) section

**Comment by JohnRiv** [comment]
In the 2019-08-21 HATF call, there was consensus to make this update.

**Comment by jpiesing** [comment]
Where a spec is dropped, either explicitly or implicitly, could we make a note of this somewhere in our spec?

**Comment by JohnRiv** [comment]
Thanks, you raise a good point.

We currently state this in Section 1.1: "There is no suggestion that APIs not included in this specification should be removed from implementations."

If we include a note or a section to mention that a spec that was dropped, we should probably clarify that sentence further. Are we suggesting that the specs that are dropped are an exception and should be removed, or just that they are no longer part of the minimum requirements?

Also, specific to this update from CSS-2017 to CSS-2018, [CSS-2018 specifically states that CSS Profiles have been discontinued](https://www.w3.org/TR/css-2018/#profiles), so I'm not sure we need to call that out in our spec since we would be duplicating what is specified in CSS-2018.

**Comment by jpiesing** [comment]
> Also, specific to this update from CSS-2017 to CSS-2018, [CSS-2018 specifically states that CSS Profiles have been discontinued](https://www.w3.org/TR/css-2018/#profiles), so I'm not sure we need to call that out in our spec since we would be duplicating what is specified in CSS-2018.

There's a difference between duplicating what is specified in CSS-2018 and referring to it. It was the latter I had in mind.

**Comment by JohnRiv** [comment]
Makes sense. I just pushed up a commit to my existing PR to add a note below the mention of CSS-2018. Here's how it will render as I currently have it staged:

<img width="832" alt="CSS-2018-9978b8d" src="https://user-images.githubusercontent.com/614632/63607244-0ae91f00-c5a0-11e9-805b-134cc0fd155d.png">

Feedback is welcome on if that is the best approach or we should communicate that differently.
