### ISSUE TITLE
Specify conformance class when needed, for HTML5.1 in particular

### ISSUE THREAD

**Issue by tidoust** [w3c-cg/webmediaapi#21]
Different classes of products may be able to claim conformance against a specification. The Web Media APIs should clarify which one it applies to avoid misinterpretations, especially since different conformance requirements apply to different classes.

For instance, [HTML5.1 defines several overlapping conformance classes](http://www.w3.org/TR/html51/infrastructure.html#conformance-classes). When we say "devices MUST support HTML5.1", I believe we mean that devices must act as "Web browsers that support the HTML syntax, (the XHTML syntax as well?), scripting", and as "Visual user agents that support the suggested default rendering".

In most other cases, this comment is probably moot because there is only one conformance class, or it is pretty obvious which one to use (for instance, CSS defines "style sheet", "authoring tool" and "renderer", and it's pretty obvious we target "renderers"). We should just check all specs.

**Comment by mavgit** [comment]
@tidoust Can you make a recommendation?

1. Are you proposing we add to this spec that 
> devices must act as "Web browsers that support the HTML syntax, (the XHTML syntax as well?), scripting", and as "Visual user agents that support the suggested default rendering"

2. What do you mean by "check all specs"?

**Comment by tidoust** [comment]
About 1., yes, right now the Web Media API spec says:

"Devices MUST support the following specifications:
- HTML 5.1 [HTML51]
- ECMAScript Language Specification, Edition 5.1 [ECMASCRIPT-5.1]"

I would complete the HTML 5.1 line to explicit the HTML 5.1 conformance criteria that devices must comply with, for instance:

"Devices MUST support the following specifications:
- HTML 5.1 [HTML51], devices acting as Web browsers that support the HTML syntax and the XHTML syntax, scripting, and the suggested default rendering,
- ECMAScript Language Specification, Edition 5.1 [ECMASCRIPT-5.1]"

About 2., I believe all other specifications referenced by the Web Media APIs only define one conformance class, so what "support" means for them should be clear. However, someone should have a quick look at these specifications to confirm that this is indeed the case.

**Comment by davemevans** [comment]
(1) is addressed by #66.

I will take a look through the other references and report back.

**Comment by davemevans** [comment]
As Francois says, other than CSS, most specs target a single conformance class - user agents - so there seems no need to clarify this.

In the CSS case, I agree that it is obvious we target renderers, so it seems unnecessary to add additional text here.

I believe merging #66 will allow this issue to be closed.

**Call for consensus:** Merge PR #66 and close issue.

**Comment by davemevans** [comment]
Consensus reached on telco 03/05/17.

Closed via 3159759.
