### ISSUE TITLE
WMAS2019 hostname

### ISSUE THREAD

**Issue by JohnRiv** [w3c-cg/webmediaapi#219]
I noticed the [final published version of the Web Media API Snapshot 2018](https://cta.tech/cta/media/EventImages/TechStandards/CTA-5000-A-Final.pdf) contains a link to the test suite at https://webapitests2018.ctawave.org/

Should we stand up https://webapitests2019.ctawave.org/ and have it initially be the same content as https://webapitests2018.ctawave.org/ to prepare for the 2019 Snapshot being published in December 2019?

**Comment by johnluther** [comment]
Agreed. You and I can coordinate w/ Alexandra at CTA to get the webapitests2019 host name, and with Fraunhaufer to set up the server.

**Comment by JohnRiv** [comment]
We will have the subdomain created and we'll need Fraunhofer to point it to the 2018 tests initially.

Also, we noted that it would be useful to have a landing page that links to the different test suites from each year that we could link to from each test suite.
