### ISSUE TITLE
what does it mean to support the fullscreen API on a TV?

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#22]
The draft currently requires support for the fullscreen API.

Support for this on TVs is complex for reasons that some may find surprising.

In TV sets, the browser is often permanently in some sort of full screen mode with no possibility to be otherwise. The WHATWG fullscreen spec has language like this;

> Resize pending’s top-level browsing context’s active document’s viewport’s dimensions to match the dimensions of the screen of the output device.

In the average browser on a TV set, this is true 100% of the time and there is no possibility for anything else.

**Comment by thasso** [comment]
Does the requirement for Fullscreen Support via WHATWG conflict with the implementations on TV sets then? Or is it basically just on all the time?

I assume this requirement is a MUST to ensure that there is fullscreen video playback support on all platforms. If WHAWG is not fully (or at all?) required, how can we ensure that _all_ platforms will support fullscreen playback?

**Comment by jpiesing** [comment]
@thasso 
> Does the requirement for Fullscreen Support via WHATWG conflict with the implementations on TV sets then? Or is it basically just on all the time?

It's basically on all the time and attempts to turn it off would fail. It's not obvious that the exitfullscreen algorithm defined in the WHATWG fullscreen spec would allow this as a reason for failure.

> I assume this requirement is a MUST to ensure that there is fullscreen video playback support on all platforms. If WHAWG is not fully (or at all?) required, how can we ensure that all platforms will support fullscreen playback?

I would not make this assumption. I see absolutely no linkage between the fullscreen API and fullscreen video playback. IMHO the way to ensure that all platforms support fullscreen video playback is to include that in the WAVE device playback specification.

**Comment by mavgit** [comment]
While I would speculate that the authors of the fullscreen spec may not have considered devices which are always in fullscreen mode, I'm not sure I see a practical conflict with this API when used on devices which are always in fullscreen mode.

If you call requestFullscreen and nothing changes because the device is always fullscreen, that seems OK to me.
If you call exitFullscreen and nothing changes because the device is always fullscreen, that also seems OK.

Calling the fullscreen API enables your app to go fullscreen both on devices that are sometimes fullscreen and also on devices that are always fullscreen.

**Comment by jpiesing** [comment]
> If you call requestFullscreen and nothing changes because the device is always fullscreen, that seems OK to me.
> If you call exitFullscreen and nothing changes because the device is always fullscreen, that also seems OK.

@mavgit I don't see how this cannot be considered subsetting by the definition that you have used elsewhere.

**Comment by mavgit** [comment]
@jpiesing said: 
> I don't see how this cannot be considered subsetting by the definition that you have used elsewhere.

I was not proposing a subset, rather a possible conforming implementation. To put it another way, the fullscreen API transitions between a fullscreen mode and a "normal" mode. If a devices "normal" mode was fullscreen, than a conforming implementation would transition between fullscreen to fullscreen.

However, this is just speculation on my part. The fullscreen spec seems to be silent on the issue of devices that are always in fullscreen mode.

I further note that iOS and Android mobile devices, which have browsers that are always (or most always) in fullscreen mode, do not implement fullscreen API. [http://caniuse.com/#feat=fullscreen](url)

I will send an email to the fullscreen author to clarify whether the fullscreen spec has a model for devices that are always fullscreen and also whether devices that are always fullscreen should simply not implement this API, as with iOS and Android mobile devices.

**Comment by davemevans** [comment]
@mavgit was there a response from the fullscreen author, and did help move this issue forward?

**Comment by davemevans** [comment]
Anne answers (and the questions):

>> 1. Does the Fullscreen API have a model for how devices that are always in fullscreen mode should implement the Fullscreen API?
>
> We don't really at the moment, though they could. An aspect of the
Fullscreen API is that it fullscreens a particular element, which has
some advantages for developers even when the application always takes
up most of the screen.
>
>> 2. Should TVs and TV-connected devices simply follow the iOS and Android model and not implement this API?
>
> I don't really know the motivation behind those platforms not exposing
the API so I'm probably not the right person to ask.

**Comment by davemevans** [comment]
> To put it another way, the fullscreen API transitions between a fullscreen mode and a "normal" mode. If a devices "normal" mode was fullscreen, than a conforming implementation would transition between fullscreen to fullscreen.

I agree with @mavgit here: if top-level browsing context’s active document’s viewport’s dimensions normally match the dimensions of the screen of the output device, the resize steps in each algorithm simply have no effect.

**Comment by mavgit** [comment]
I agree with @bbcrddave regarding fullscreen of the top-level browsing context sometimes being null.

Note also that even on devices where the top-level browsing context is always full screen, the fullscreen API still has a usage for transitioning the video portion of the app between full screen size and smaller sizes (also known as "inset video" or "picture in graphics"), since as Anne points out:

> An aspect of the Fullscreen API is that it fullscreens a particular element, which has some advantages for developers even when the application always takes up most of the screen.

I Call for Consensus to close this issue with no change, since the fullscreen API has defined usage on any screen, whether or not the app always runs in full screen mode.

**Comment by davemevans** [comment]
Consensus reached by those on telco 03/05/17.
Issue will be closed with no action on 05/05/17 if no further feedback via GitHub.

**Comment by jpiesing** [comment]
I'm not convinced about this.

**Comment by davemevans** [comment]
Could you elaborate on the specific concern you have? The behaviour you describe in the OP appears to be acceptable according to the specification?

**Comment by davemevans** [comment]
Consider Chrome when launched (on a non-Android platform) with the  `--kiosk` argument. The browser is permanently in full screen mode with no possibility to be otherwise.

The Fullscreen API functions correctly under these circumstances.

**Comment by jpiesing** [comment]
> Consider Chrome when launched (on a non-Android platform) with the --kiosk argument. The browser is permanently in full screen mode with no possibility to be otherwise.
> The Fullscreen API functions correctly under these circumstances.

What does  exitFullscreen() do in these circumstances?

**Comment by mavgit** [comment]
FYI, I tried out a [fullscreen demo page](http://html5-demos.appspot.com/static/fullscreen.html) when Google Chrome is in kiosk mode and it seems to do the right thing.

The demo page shows the fullscreen API being used on two elements (a video element and an iframe element) that are not the top-level browsing context. requestFullscreen() on either element brings that element to full screen. A subsequent exitFullscreen() on either element returns that element to it's original size within the top-level browsing context, while the top-level browsing context remains full screen as maintained by the kiosk mode.

So, kiosk mode seems to be an override of the fullscreen API only for the top-level browsing context, making fullscreen calls to the top-level browsing context do nothing. All other elements continue to work as expected with the fullscreen API, with or without kiosk mode. This seems to be the behavior one would want.

Therefore, I again propose we close this issue without change.

**Comment by jpiesing** [comment]
But is this behaviour compatible with the spec?

**Comment by davemevans** [comment]
When in kiosk mode, the top level document's viewport dimensions match that of the display. Therefore, when requestFullscreen or exitFullscreen are called the resize step of each algorithm has no effect, whilst all other steps occur as expected.

**Comment by davemevans** [comment]
Note that I was simply drawing an analogy between kiosk mode and the normal operation of a TV rather than suggesting a special mode of operation.

Further, this mode is not overriding the full screen API to do nothing - it merely sets the 'normal' viewport dimensions of the top level document to match the display, so no resize occurs.

**Comment by mavgit** [comment]
@bbcrddave 
> Further, this mode is not overriding the full screen API to do nothing - it merely sets the 'normal' viewport dimensions of the top level document to match the display, so no resize occurs.

You're correct. I was wrong. The fullscreen API operates the same whether the browser is in kiosk mode or not. The kiosk mode doesn't need to override anything. This is as described in the algorithm steps in the fullscreen spec.

So, can we close this issue now?

**Comment by davemevans** [comment]
> So, can we close this issue now?

@jpiesing?

**Comment by jpiesing** [comment]
@bbcrddave @mavgit Please give me until the next call to find the time needed to go through this issue slowly & carefully. If not then I'll shut up.

**Comment by jpiesing** [comment]
I agree with @bbcrddave 's conclusion that an implementation without any browser chrome can just have the top level document's "normal" dimensions be the same as "the dimensions of the screen of the output device" and so I withdraw my objection to supporting this API. I'm not sure we can close the issue though for two reasons.
- Having the normal dimensions be the same as the dimensions of the screen is not remotely obvious and IMHO people will miss this if it's not pointed out.
- Support for the API doesn't mean a request to full screen (say) a video element is guaranteed to succeed. If you look at step 6 of the requestFullScreen algorithm, the last of the 4 sub-steps refers to https://fullscreen.spec.whatwg.org/#fullscreen-is-supported which says "Fullscreen is supported
if there is no previously-established user preference, security risk, or platform limitation. " Is it reasonable for this test to fail on a WAVE device?

**Comment by mavgit** [comment]
Consensus to add implementation notes on the two bullets above.

**Comment by mavgit** [comment]
Call for Consensus:

Since we've now started the Porting spec and since both these bullet points relate to implementation/porting of the user agent, I suggest that:
1. We close this issue in this Web Media API issue tracker with no change, and
2. Jon is invited to resubmit these two bullet points into the [Porting spec issue tracker](https://github.com/w3c/webmediaporting/issues).
