### ISSUE TITLE
reopening IMSC subtitle/caption rendering appears to need(?) VTTCue class which is not in our spec

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#221]
Since I can't reopen #211 , it seems I have no choice but to create the same issue again.

I don't find the explanation from the f2f meeting of why it was closed to be convincing.
Also closing an issue without the original proposer present & without giving them an opportunity to comment is IMHO unreasonable.

**Comment by JohnRiv** [comment]
Hi @jpiesing, sorry I missed the notification that you commented further on the previous issue. I'll reopen #211 and close this so we can keep the conversation in one place.
