### ISSUE TITLE
consider updating security specs

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#223]
Currently we have 2 security specs listed.

> Devices MUST be conforming implementations of the following specifications:
> 
>     Content Security Policy Level 2 [CSP2]
>     Web Cryptography API [WEBCRYPTOAPI]
> 

At some point we should review this list (not necessarily for the 2019 version). The following appear to be widely supported. 

1) Subresource integrity

https://caniuse.com/#feat=subresource-integrity

Supported in Firefox as of v 43, Dec 2015
Supported in Chrome as of v 45, September 2015
Supported in Safari as of v 11, September 2017
Supported in Edge since v 17, April 2018

2) TLS 1.3

https://caniuse.com/#feat=tls1-3

Supported in Firefox as of v 63, October 2018.
Supported in Chrome as of v 70, October 2018
Supported in Safari as of 12.1, March 2019, only on MacOS 10.14 and higher
In development in Edge

3) Referrer Policy, Candidate Recommendation, 26-January-2017, Jochen Eisinger, Emily Stark

https://caniuse.com/#feat=referrer-policy

Supported in Firefox as of v 36, Feb 2015
Supported in Chrome as of v 61, Sept 2017
Supported in Safari as of v 11.1, Mar 2018
Old version supported in Edge

4) Upgrade Insecure Requests, Candidate Recommendation, 08-October-2015, Mike West

https://caniuse.com/#feat=upgradeinsecurerequests

Supported in Firefox as of v 42, November 2015
Supported in Chrome as of v 43, May 2015
Supported in Safari as of v 10.1, March 2017
Supported in Edge as of v17, April 2018.

**Comment by JohnRiv** [comment]
In the 2019-10-30 HATF call, we decided to add "Subresource integrity" and "grade Insecure Requests" for 2019 since they have full UA support, and defer the additional ones (including others we may have not yet identified) until 2020.

**Comment by JohnRiv** [comment]
To reiterate the above, I've added a call-for-consensus label to include "Subresource integrity" and "Upgrade Insecure Requests" in WMAS2019. Assuming that gets in, we'll create a new issue to track adding "TLS 1.3" and "Referrer Policy" into a future edition.

**Comment by JohnRiv** [comment]
Closing this, as 1 & 4 were handled by PR #226 and 2 & 3 have been copied over to #229 for tracking against WMAS2020
