### ISSUE TITLE
WMAS 2019 referring to snapshots of WHATWG living specs

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#224]
We've had a discussion many times about WHATWG living specs not being suitable for use-cases that rely on having a stable document.

I've recently been reminded of this because WMAS 2018 just refers to WHATWG HTML and effectively automatically picks up all changes to that document. This isn't suitable as-is for something that could be indirectly referenced in contracts or regulation.

I notice that the WHATWG / W3C arrangement refers to periodic snapshots. I can't find any copies of such a periodic snapshot although there is a github issue that implies they exist - https://github.com/w3c/i18n-activity/issues/781 .

Alternatively the WHATWG working document [1] allows for this as follows;

> Consumers who need to reference exactly what a Living Standard said at a given point in time, for example to document what they implemented from or to explain the history of the web platform, can use the commit snapshots functionality. Each Living Standard has a "Snapshot as of this commit" link that gives a frozen copy for such historical reference. The WHATWG will keep these snapshots available at their published URLs permanently. However, other standards organizations are discouraged from referencing these snapshots, as they generally contain contain known issues that have been fixed in the Living Standard, and can mislead implementers and web developers. 

An example of this is here - https://html.spec.whatwg.org/commit-snapshots/ead4aa8ec576d7d330a04f7ec8508e336b895fdb/

This has a banner saying not to use it - "This document contains the contents of the standard as of the ead4aa8ec576d7d330a04f7ec8508e336b895fdb commit, and should only be used as a historical reference. This commit may not even have been merged into master.

Do not attempt to implement this version of the standard. Do not reference this version as authoritative in any way. Instead, see https://html.spec.whatwg.org/ for the living standard."

Either way, WAVE should consider modifying the references to living standards to refer to require versions as of a certain date or later.

[1] https://whatwg.org/working-mode

**Comment by JohnRiv** [comment]
Thanks @jpiesing. My understanding is w3c/i18n-activity#781 is the beginnings of the first such snapshot of HTML since the [agreement between the W3C and WHATWG was announced](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/). Once that reaches a W3C recommendation then we absolutely should reference the latest W3C snapshot instead of the WHATWG living standard. That first snapshot is [tentatively scheduled to be published in Q1 2020](https://www.w3.org/2018/12/html.html).

**Comment by JohnRiv** [comment]
In the 2019-10-30 HATF call, we decided WMAS2019 should include a note that the reference to WHATWG standards should require a version of it on a specific date "or later."
