### ISSUE TITLE
SVG 1.1 requirement incompatible with HTML5

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#225]
WMAS 2019 draft says;

>Devices MUST be conforming implementations of the following specifications:
...
> Scalable Vector Graphics (SVG) 1.1 (Second Edition) [SVG11]

This conflicts with WHATWG HTML which says;

> The semantics of SVG elements are defined by SVG 2 and other applicable specifications. [SVG]

This is more serious than it appears because if you look back at W3C HTML 5.1, that says;

> 
> User agent requirements: SVG as implemented today follows neither SVG 1.1 nor SVG Tiny 1.2 precisely, instead implementing subsets of each. Although it is hoped that the in-progress SVG 2 specification is a more realistic target for implementations, until that specification is ready, user agents must implement the SVG 1.1 specification with the following willful violations and additions. [SVG11] [SVGTiny12] [SVG2]
> 
> The following features from SVG 1.1 must not be implemented:
> 
>     The tref element
>     The cursor element (use CSS’s cursor property instead)
>     The font-defining elements: font, glyph, missing-glyph, hkern, vkern, font-face, font-face-src, font-face-uri, font-face-format, and font-face-name (use CSS’s @font-face instead)
>     The externalResourcesRequired attribute
>     The enable-background property
>     The contentScriptType and contentStyleType attributes (use the type attribute on the script and style elements instead) 
> 
> The following features from SVG Tiny 1.2 must be implemented:
> 
>     The non-scaling-stroke value for the vector-effect property
>     The class attribute is allowed on all SVG elements
>     The tabindex attribute is allowed on visible SVG elements
>     The ARIA accessibility attributes are allowed on all SVG elements 

I think we should remove the reference to SVG from WMAS and fall back on the reference to it in the HTML spec.

If we would fix bugs in WMAS 2018 then that has the same problem. WMAS 2017 doesn't reference SVG.

**Comment by JohnRiv** [comment]
In the 2019-10-30 HATF call, we decided to remove the reference to SVG from WMAS2019
