### ISSUE TITLE
subsetting workers

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#23]
The spec currently requires support for workers;
> Devices MUST support the following specifications:
>     Web Storage [WEBSTORAGE]
>     Web Workers [WORKERS]

In HbbTV/OIPF, the workers spec was subset to make support for shared workers optional.
> Support for Shared Workers is OPTIONAL

If I look at caniuse for shared workers - http://caniuse.com/#search=sharedworkers - it shows them as supported in Firefox, Chrome and Opera but not elsewhere. Further it indicates that shared workers were removed from webkit - https://webkit.org/status/#feature-shared-web-workers .

**Comment by davemevans** [comment]
~~The precedents we have set so far are:~~
* ~~if any of the big four do not have support, we cannot require the API~~
* ~~we don't wish to subset specifications.~~

~~So the fix for this seems pretty straightforward - make Web Workers optional. I'll create a PR, and we can discuss it on the next call.~~

See note below after further consideration.

**Comment by jpiesing** [comment]
@bbcrddave Sorry but I don't think we should make them optional. We should make shared workers an "exception" in the same way as compound keys in IndexedDB. Also I very strongly object to a precedent of not subsetting - I think that is just unrealistic when you look at real world examples.

**Comment by davemevans** [comment]
Thinking about this some more, adding an exception would probably solve this so perhaps I was a bit hasty in my PR.

However, as you said over at https://github.com/w3c/webmediaapi/issues/4#issuecomment-277630084, making exceptions and subsetting feel very similar to me. The CG needs to decide what is going to be acceptable. We should nail this down on the next call.

Personally, I tend to agree that Web Workers should be required.

**Comment by davemevans** [comment]
08/02: It was suggested that we don't need to make an exception and app developers can just detect missing APIs in a particular engines if there is broad support elsewhere. So perhaps we don't need to make any statement.

Next step: **input requested from CG membership.**

**Comment by davemevans** [comment]
No input received in two weeks.

<b>Call for consensus:</b> This issue will be closed with no further action after the call tomorrow if there are no objections.

**Comment by jpiesing** [comment]
As the originator of this issue, I don't agree. This has significant implications for testing WAVE devices.

**Comment by mavgit** [comment]
@bbcrddave said:
> It was suggested that we don't need to make an exception and app developers can just detect missing APIs in a particular engines if there is broad support elsewhere. So perhaps we don't need to make any statement.

I agree with this approach. It is important for us to state in our spec which APIs we feel are important for inclusion, so I agree with including Web Workers as an important spec.

However, I don't think it makes sense to try to go beyond spec inclusion and have our spec detail the current implementation status of each individual API of each spec across every web client code base. Given that the various web client code bases update multiple times a week, any such snapshot will be out of date before it's published and be completely useless to both app programmers and device implementors.

App programmers already have better resources to track implementation status:
- Data-driven websites, like caniuse.com, are better engineered to be a much more accurate, up-to-date reference for programmers on web client implementation status than any infrequently published spec.
- Existing JavaScript polyfill libraries are continuously updated to support current and previous client releases.
- Testing for APIs before using is a recommended and common programming practice.

Device implementors who port a client library don't make changes to the client library itself. For example, if a TV manufacturer is porting a web client library to their TV and that library has an incomplete implementation of Web Workers, the TV manufacturer is not going to complete the implementation of Web Workers.

**Comment by jpiesing** [comment]
> Device implementors who port a client library don't make changes to the client library itself. For example, if a TV manufacturer is porting a web client library to their TV and that library has an incomplete implementation of Web Workers, the TV manufacturer is not going to complete the implementation of Web Workers.

I agree, that's why we should call out service workers as something that does not need to be present. Explicitly calling out exceptions makes the spec useful when a device implementer is negotiating with a supplier who has a pre-existing port. Not calling out exceptions effectively means anything can be an exception.

**Comment by jpiesing** [comment]
> Device implementors who port a client library don't make changes to the client library itself. For example, if a TV manufacturer is porting a web client library to their TV and that library has an incomplete implementation of Web Workers, the TV manufacturer is not going to complete the implementation of Web Workers.

I agree 100% but don't see how this is relevant.

If we say nothing and just require Workers (and follow the same precedent elsewhere for specs where significant features / functions are not implemented in the real world) then then device implementers & their suppliers will assume that they can do any subsetting that is convenient to them. It will also make our spec useless as a mechanism for manufacturers to push suppliers to move to a more modern browser.
An opportunity to encourage TV browsers to keep up with the modern web will have been lost.

**Comment by mavgit** [comment]
@jpiesing I agree 100% with your goal to have our spec motivate device implementers and suppliers to use more modern browsers and not to subset. I think our difference is that I'd like to see if we can achieve this goal by focussing on testing a carefully-chosen subset of the entire API rather than the entire API.

**Comment by jpiesing** [comment]
>  I agree 100% with your goal to have our spec motivate device implementers and suppliers to use more modern browsers and not to subset. I think our difference is that I'd like to see if we can achieve this goal by focussing on testing a carefully-chosen subset of the entire API rather than the entire API.

Unfortunately I don't think that's our difference at all.

I think subsetting is a reality (Shared Workers aren't in webkit) and either we acknowledge that (and similar examples) in our spec or people will use the fact that we don't to justify far more subsetting.

**Comment by boyofgreen** [comment]
Edge does also not support shared workers, and has no plans at this time:
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/sharedwebworkers/?q=shared%20%20web%20worker

**Comment by hober** [comment]
Subsetting sounds good to me.

**Comment by davemevans** [comment]
Consensus reached on 22/03/17 telco to require Web Workers with a note saying that Shared Workers are not required.

Next step: create PR.

**Comment by mavgit** [comment]
I would like us not to use the word "subsetting" or any equivalent term, because I don't think it's what we're doing. Also, the W3C TAG has recently stated the need to "refrain from subsetting the web platform." (See issue #39)

I like the term exceptions better, because what we're actually doing is noting an exception in our testing.

For example, we're not making a case for whether or not shared workers is part of the standard Web APIs. We're also not defining a subset of the Web that excludes web workers. We're instead recognizing that web workers are not currently implemented across all web platforms and consequently, we will not test for web workers as part of our tests.

These exceptions could be titled: **APIs not to be tested due to insufficient cross-platform support:** or the equivalent.

**Comment by davemevans** [comment]
Closed via  3d1bb3a.
