### ISSUE TITLE
chain of references heading out into specs not implemented in all codebases

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#230]
This is not a bug report against WMAS 2019, just something we should think about.

If you look at the current version of the service workers spec, you find language like this ...

> 4.7. Events
> 
> The following events, called service worker events, are dispatched on ServiceWorkerGlobalScope object:
> push | PushEvent | Functional | (See Firing a push event.)
> sync | SyncEvent | Functional | (See Firing a sync event.)

> [push] defines the following terms:
>  push 

[push] is not reference in the spec & neither is sync.

If you look at an older version, e.g. https://www.w3.org/TR/2017/WD-service-workers-1-20171102/, that still has the reference to [push] although without the mention of the events.

I'm sure there will be other examples of this.

We may want to consider a generic statement that references from WMAS may in turn (recursively) include specs not implemented in all codebases and that this is understood & accepted. Perhaps we might then give service workers and push API as an example.

Background sync is only in chrome-based browsers & push API is not in Safari.

https://caniuse.com/#feat=push-api
https://caniuse.com/#feat=background-sync

**Comment by JohnRiv** [comment]
This requires further research to determine how many more cases like this potentially exist. Then we can determine the best way to document it.

**Comment by JohnRiv** [comment]
In my brief attempts to research this, it seems we can continue to find cases without much trouble (I found one in a matter of minutes... the [Web Audio API](https://www.w3.org/TR/webaudio/) references [Worklets](https://www.w3.org/TR/worklets-1/) and those are [only supported in Chromium browsers](https://developer.mozilla.org/en-US/docs/Web/API/Worklet#Browser_compatibility)).

A general note as @jpiesing suggested seems to be the best way to acknowledge this, as there is no straightforward way to solve it. Pulling from his original suggestion, I propose we add something along these lines as an additional paragraph to the Introduction section of [Section 3. Web Media APIs currently supported on all platforms](https://w3c.github.io/webmediaapi/#web-media-apis-currently-supported-on-all-platforms)

> In addition, the specifications of the web APIs mentioned here may in turn (recursively) reference other specifications that are not supported across all four of the most widely used user agent code bases. This possibility is understood and accepted. For example, Service Workers 1 [[SERVICE-WORKERS-1](https://w3c.github.io/webmediaapi/#bib-service-workers-1)] references the `push` event from the [Push API](https://w3c.github.io/push-api/), but the Push API is not yet widely supported. These unsupported referenced specifications will not be cited as exceptions in this specification, and will not be tested as part of our tests.

**Comment by jpiesing** [comment]
Here is a possible improvement to the last sentence of the proposed note.
> These unsupported referenced specifications are not explicitly cited as exceptions in this specification but, in spite of this, will not be tested as part of our tests.

**Comment by JohnRiv** [comment]
On the 2/19/20 HATF call, there was consensus to merge the PR.
