### ISSUE TITLE
differences between HbbTV and WMAS 2018 (1) - text-shadow

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#236]
The 2013 web standards profile used by HbbTV until now includes text-shadow from CSS Text [CSS3TEXT-20121113].
Since then, text-shadow has been moved to CSS3 text decoration which is not in WMAS.

https://www.w3.org/TR/css-text-decor-3/#text-shadow-property

Formally CSS3 Text Decoration is a W3C Candidate Recommendation. In the CSS 2018 snapshot, it is under the heading "The following modules have completed design work, and are fairly stable, but have not received much testing and implementation experience yet: ".

text-shadow is supported in all browsers according to 
https://caniuse.com/#feat=mdn-css_properties_text-shadow and 
https://caniuse.com/#feat=css-textshadow

If HbbTV would move to reference WMAS then it would need to add text-shadow on top of what is in WMAS and not use WMAS as-is.

Please can WAVE consider adding text-shadow.

**Comment by JohnRiv** [comment]
Consider referencing CSS Text Decoration Module Level 3 with an "exception" that we would only support text-shadow

**Comment by JohnRiv** [comment]
I'll put together a PR to address this

**Comment by JohnRiv** [comment]
For historical reference and to assist our future selves, the following is a list of the other features that are part of CSS Text Decoration Module Level 3 and links to their browser support that show they do not have full support of the top 4 UAs as of the end of 2019:

- [`text-decoration-line`](https://www.w3.org/TR/css-text-decor-3/#text-decoration-line-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=mdn-css_properties_text-decoration-line)
- [`text-decoration-style`](https://www.w3.org/TR/css-text-decor-3/#text-decoration-style-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=mdn-css_properties_text-decoration-style)
- [`text-decoration-color`](https://www.w3.org/TR/css-text-decor-3/#text-decoration-color-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=mdn-css_properties_text-decoration-color)
- [`text-decoration` shorthand](https://www.w3.org/TR/css-text-decor-3/#text-decoration-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=text-decoration)
- [`text-underline-position`](https://www.w3.org/TR/css-text-decor-3/#text-underline-position-property) - [caniuse.com shows support for all but Firefox & Safari](https://caniuse.com/#feat=mdn-css_properties_text-underline-position)
- [`text-emphasis-style`](https://www.w3.org/TR/css-text-decor-3/#text-emphasis-style-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=mdn-css_properties_text-emphasis-style)
- [`text-emphasis-color`](https://www.w3.org/TR/css-text-decor-3/#text-emphasis-color-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=mdn-css_properties_text-emphasis-color)
- [`text-emphasis` shorthand](https://www.w3.org/TR/css-text-decor-3/#text-emphasis-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=mdn-css_properties_text-emphasis)
- [`text-emphasis-position`](https://www.w3.org/TR/css-text-decor-3/#text-emphasis-position-property) - [caniuse.com shows support for all but Edge](https://caniuse.com/#feat=mdn-css_properties_text-emphasis-position)

**Comment by JohnRiv** [comment]
On the 2/19/20 HATF call, there was consensus to merge the PR.

Note for the 2020 spec update, once caniuse.com is updated, it appears we'll have more aspects of CSS Text Decoration Module Level 3 to support. We'll open a new issue for that when appropriate.
