### ISSUE TITLE
differences between HbbTV and WMAS 2018 (2) - Media Fragments

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#237]
WMAS lists Media Fragments URI 1.0 (basic) under APIs that "are not yet implemented in all four code bases. ".

HbbTV requires support for the simplest part of this - "Terminals SHALL support temporal clipping based on Normal Play Time as defined in section 4.2.1 of the Media Fragments URI specification [MEDIA-FRAGS-20120925]."

caniuse.com suggests this simplest part is implemented everywhere except Edge - https://caniuse.com/#feat=media-fragments .

The Edge web site says there is partial implementation without giving any details. https://developer.microsoft.com/en-us/microsoft-edge/platform/status/mediafragments/

Section C.4 of MPEG-DASH defines "MPD anchors" which use media fragments to enable more precise specification of the initial presentation of DASH content as follows;

> 42nd second of Period1 my.mpd#t=42&period=Period1
> my.mpd#t=42&period=Period1
> 
> 42nd second from the start of the presentation, English 5.1 audio and video
> my.mpd#t=42&track=en51&track=vid
> 
> A range from 60s to 180s of the presentation
> my.mpd#t=60,180
> 
> Start a live stream at Wed, 21 Jan 2015 20:04:05 GMT
> my.mpd#t=posix:1421870645

I have no idea how #period works in combination with MSE and dash.js / shakaplayer.

If HbbTV would move to reference WMAS then it would need to add t=n,n on top of what is in WMAS and not use WMAS as-is.

Media fragments are in HTML5 / WHATWG HTML in a way that is very confusing.

> Media fragment syntax is defined in Media Fragments URI. [MEDIAFRAG]
> The id attribute returns the track's identifier, if it has one, or the empty string otherwise. For tracks that correspond to track elements, the track's identifier is the value of the element's id attribute, if any. For in-band tracks, the track's identifier is specified by the media resource. If the media resource is in a format that supports media fragment syntax, the identifier returned for a particular track must be the same identifier that would enable the track if used as the name of a track in the track dimension of such a fragment.
> If either the media resource or the URL of the current media resource indicate a particular set of audio tracks to enable, or if the user agent has information that would facilitate the selection of specific audio tracks to improve the user's experience, then: if this audio track is one of the ones to enable, then set enable to true, otherwise, set enable to false.
> Example: This could be triggered by media fragment syntax, but it could also be triggered e.g. by the user agent selecting a 5.1 surround sound audio track over a stereo audio track.
> If either the media resource or the URL of the current media resource indicate a particular set of video tracks to enable, or if the user agent has information that would facilitate the selection of specific video tracks to improve the user's experience, then: if this video track is the first such video track, then set enable to true, otherwise, set enable to false.
> Example: This could again be triggered by media fragment syntax.
> If either the media resource or the URL of the current media resource indicate a particular start time, then set the initial playback position to that time and, if jumped is still false, seek to that time.
> Example: For example, with media formats that support media fragment syntax, the fragment can be used to indicate a start position.
> 4.8.12.10.2 Selecting specific audio and video tracks declaratively
> The audioTracks and videoTracks attributes allow scripts to select which track should play, but it is also possible to select specific tracks declaratively, by specifying particular tracks in the fragment of the URL of the media resource. The format of the fragment depends on the MIME type of the media resource. [RFC2046] [URL]
> Example: In this example, a video that uses a format that supports media fragment syntax is embedded in such a way that the alternative angles labeled "Alternative" are enabled instead of the default video track.
> <video src="myvideo#track=Alternative"></video>

Please can WAVE consider moving at least the t=n,n piece of media fragments from "not yet implemented" to required.

**Comment by JohnRiv** [comment]
In the 12/11/19 HATF call we agreed to close this
