### ISSUE TITLE
 differences between HbbTV and WMAS 2018 (3) - Notifications

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#238]
WMAS requires support for notifications. While some media device operating systems have a notifications mechanism (e.g. Android TV), others do not. WMAS as written would appear to require adding a notifications mechanism where the operating system does not have one.

Some media devices may support multiple HTML pages loaded at the same time where one (or more) are visible and others are not visible but can still execute. Supporting notifications on these makes some kind of sense. If an media device only supports one HTML page loaded at one time and that page is always visible then it's hard to see there are any benefits from supporting notifications.

There's no obvious way to have a "stub" implementation. If the permissions are set to default then there's a requirement to ask the user.
> If permission is "default", ask the user whether showing notifications for the entry settings object’s origin is acceptable. If it is, set permission to "granted", and "denied" otherwise. 

HbbTV uses notifications but only in combination with Operator Applications - which run in a separate tab from the regular apps and which can execute while not visible.

Please reconsider the requirement for notifications to be mandatory in WMAS.

**Comment by JohnRiv** [comment]
Consider recommendation for how to handle the use case where the OS itself does not support notifications. Some research to see how it has been handled by others would be useful.

**Comment by jpiesing** [comment]
This seems to cover some of this issue - https://github.com/whatwg/notifications/issues/116 .

**Comment by JohnRiv** [comment]
I'll work on a PR to add a note to the spec cautioning developers about this. A reference to the WHATWG convo above could be useful

**Comment by JohnRiv** [comment]
On the 2/19/20 HATF call, there was consensus to merge the PR.
