### ISSUE TITLE
HbbTV spec made some parts of CSS Basic User Interface optional

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#24]
HbbTV/OIPF made some parts of CSS3 Basic User Interface optional as follows;
- appearance
- padding-box (marked as at-risk in an old version of HTML5)
- content (marked as at-risk in an old version of HTML5)
- icon (marked as at-risk in an old version of HTML5)
- outline-style ("At this time outline-style SHALL be supported as defined by CSS2.1 specification, so support for value auto is not required.")
- resize
- ime-mode (marked as at-risk in an old version of HTML5)
- text-overflow ("Support for the text-overflow property value <string> and the text-overflow property 2-value syntax and definition is OPTIONAL (marked as feature at risk in [CSS3UI-20120117]).")

Cross-referencing these against the current version of the CSS3 Basic UI spec;
> - appearance

This has been dropped from the CSS3 Basic UI spec.
> - padding-box value of box-sizing property (marked as at-risk in an old version of HTML5)

This has been dropped from the CSS3 Basic UI spec.
> - extension of content property to support icon (marked as at-risk in an old version of HTML5)

This has been dropped from the CSS3 Basic UI spec.
> - icon property (marked as at-risk in an old version of HTML5)

This has been dropped from the CSS3 Basic UI spec.
> - auto value for outline-style property ("At this time outline-style SHALL be supported as defined by CSS2.1 specification, so support for value auto is not required.")

This is still in the CSS3 basic UI spec. "In addition, in CSS3, outline-style accepts the value auto. The auto value permits the user agent to render a custom outline style, typically a style which is either a user interface default for the platform, or perhaps a style that is richer than can be described in detail in CSS"

TV devices may not have a meaningful 'auto' style.
> - resize

This is still in the CSS3 basic UI spec. "The resize property allows the author to specify whether or not an element is resizable by the user, and if so, along which axis/axes."

I have no idea how a TV device UI could support resizing of an element.
> - ime-mode property (marked as at-risk in an old version of HTML5)

This is still in the CSS3 basic UI spec but labelled as ""ime-mode" is a property somewhat implemented in some browsers, that is problematic and officially obsoleted by this specification." and "User agents should not support the ime-mode property.".
> - text-overflow ("Support for the text-overflow property value <string> and the text-overflow property 2-value syntax and definition is OPTIONAL (marked as feature at risk in [CSS3UI-20120117]).")

This is still at risk in the current spec ("Note: The <string> value, and the 2-value syntax "{1,2}" and functionality are all at risk.")

**Comment by jpiesing** [comment]
I think there is a general issue of things that are "at risk" so have created issue #25 for discussion of that general issue.

**Comment by davemevans** [comment]
Closed via  3d1bb3a which includes a general statement about features at risk .
