### ISSUE TITLE
consider adding Beacon API to WMAS

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#244]
The Beacon API was apparently implemented in all browser codebases - the last being Safari where it is reported as landing in v11.1 (March 2018).

https://caniuse.com/#feat=beacon

Media devices may have multiple reasons for terminating an app & support for the beacon API would make it easier for analytics to be properly reported.

**Comment by JohnRiv** [comment]
At quick glance, it appears the only API from the W3C Web Performance Working Group that we reference is the Page Visibility API. We should do a full analysis of [their APIs](https://www.w3.org/webperf/) that have reached at least "Candidate Recommendation" status and see which ones have support of the 4 major UAs.

**Comment by JohnRiv** [comment]
We will track this as part of #247
