### ISSUE TITLE
general issue of features that are 'at risk'

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#25]
Should we make a general statement about features that are labelled as 'at risk' in specifications that are not a Recommendation? The HbbTV/OIPF spec generally made these optional on a case-by-case basis. 
If we cannot agree to making them optional, can we agree they won't be tested (or at least passing the test won't be required for 'passing' the test suite).

**Comment by davemevans** [comment]
Closed via  3d1bb3a.
