### ISSUE TITLE
CSS transforms and the <video> element

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#273]
Would we expect CSS transforms to work on the &lt;video> element on media consumption devices using hardware video decoding? What about DRM protected content?
Might UHD be different from SD/HD? (e.g. a different media pipeline)
If they would work (to some extent), might there be limitations with graphics overlaying transformed video?

**Comment by JohnRiv** [comment]
If anyone creates a test page for this, please share so we can get a sense of how devices currently handle this.

**Comment by jpiesing** [comment]
Some thoughts ...
In a desktop browser, transforms and video decoding may be both be done in the UA in which case these will probably work but the implementation won't be immediately portable to a media consumption device with a hardware video decoder as the implementation in the UA would have to be replaced by a link to the hardware one. i.e. this isn't something that would 'accidentally' work due to the architecture of the implementation.
Since most (all?) media consumption devices support scaling and position of video, a 2d transform that just scales & positions video could work in theory but perhaps not in practice if the UA porting API needs changing.

This is a proposal I made to HbbTV.

> Applying CSS transforms to video elements (e.g. rotate, scale, skew, or translate) is not required to be supported.
> Simple transforms such as 2D translate and 2D scale will likely work within the video scaling requirements defined in Table 11 "Minimum terminal capabilities". More complex requirements such as 2D matrix, 2D rotate, 2D skew or any of the 3D transforms may not work at all or may be limited to unencrypted content and/or HD or even SD content or may result in dropped frames.

**Comment by JohnRiv** [comment]
That is a good point. I assume even if we tested on a few devices it wouldn't be enough of a sample to fully understand it. Based on your HbbTV proposal, should we just do something simple for WMAS2021 like this:

- CSS Transforms Module Level 1 [[CSS-TRANSFORMS-1](https://w3c.github.io/webmediaapi/#bib-css-transforms-1)]
  - Exception: applying CSS transform functions to video elements is not required to be supported.

or provide a more involved explanation of limitations:

- CSS Transforms Module Level 1 [[CSS-TRANSFORMS-1](https://w3c.github.io/webmediaapi/#bib-css-transforms-1)]
  - Exception: applying CSS transform functions to video elements is not required to be supported. Attempting to apply CSS transform functions to the video element may not work at all or may be limited to unencrypted content and/or HD or even SD content or may result in dropped frames.

**Comment by jpiesing** [comment]
@JohnRiv I have a mild preference for the second of your proposals but could also accept the first one. Please note that I improved the English of my proposal to HbbTV as follows.

> More complex requirements such as 2D rotate, 2D skew or any of the 3D transforms may not work at all or may be limited to unencrypted content and/or to HD / SD content or even to only SD content . They may also result in dropped frames.

**Comment by poolec** [comment]
In my view, there is no reason why linear scaling and translation should not work - CSS transforms are just one of many ways HTML and CSS can change the position and size of elements.  These should be handled entirely within the layout engine in the browser.  I agree with Jon that 2D rotations, skews and 3D transforms are a different matter and would need special handling to be supported on platforms in which video is output to a separate hardware-composed plane to the graphics.

I would therefore propose a slightly more limited exception:

> Exception: applying CSS transform functions other than scaling and translation to video elements is not required to be supported.  2D rotate, 2D skew or any of the 3D transforms may not work at all or may be limited to unencrypted content and/or to HD / SD content or even to only SD content. They may also result in dropped frames.


If we want to be even more precise about what scaling and translation is in the context of the CSS transforms spec, we could write:

> Exception: Applying CSS transforms to video elements is only required to be supported where the transform subjects the video element to pure 2D translation and scaling, i.e. only those combinations of transforms for which the video element's current transformation matrix (see CSS Transforms clause 3) is of the form:
> ```
>      a 0 0 e
>      0 d 0 f
>      0 0 1 0
>      0 0 0 1
> ```
> 
> More complex requirements such as 2D rotate, 2D skew or any of the 3D transforms may not work at all or may be limited to unencrypted content and/or to HD / SD content or even to only SD content . They may also result in dropped frames.

This wording was proposed to HbbTV for the next revision of their spec and in my view is more appropriate to the next iteration of the WMAS.

**Comment by JohnRiv** [comment]
@poolec thanks for your comments. Since it's possible they may not work, unless we have a way to test it on a number of devices, we're planning to go with @jpiesing's latest suggestion for WMAS2021. If we find scaling and translation do work in all devices that we test, we can propose that for a later WMAS revision. I'll put up a PR later today.

**Comment by JohnRiv** [comment]
PR #290 is now up for review. The current version of the test I've proposed in that PR is:

- CSS Transforms Module Level 1 [[CSS-TRANSFORMS-1](https://w3c.github.io/webmediaapi/#bib-css-transforms-1)]
  - Exception: applying CSS transform functions to `video` elements is not required to be supported. More complex requirements such as <a href="https://www.w3.org/TR/css-transforms-1/#funcdef-transform-rotate">2D rotate</a>, <a href="https://www.w3.org/TR/css-transforms-1/#funcdef-transform-skew">2D skew</a> or any of the 3D transforms may not work at all or may be limited to unencrypted content and/or to HD / SD content or even to only SD content. They may also result in dropped frames.

**Comment by JohnRiv** [comment]
Closed via #290
