### ISSUE TITLE
is requiring support for 100% accurate video seeking reasonable with hardware video decoders?

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#28]
HTML5 random access to video has two modes controlled by the 'approximate-for-speed' flag.
>The fastSeek() method must seek to the time given by the method’s argument, with the approximate-for-speed flag set.

and

> If the approximate-for-speed flag is set, adjust the new playback position to a value that will allow for playback to resume promptly. If new playback position before this step is before current playback position, then the adjusted new playback position must also be before the current playback position. Similarly, if the new playback position before this step is after current playback position, then the adjusted new playback position must also be after the current playback position.
> For example, the user agent could snap to a nearby key frame, so that it doesn’t have to spend time decoding then discarding intermediate frames before resuming playback.
> 

Decoding from a RAP (or equivalent) to the requested frame while discarding the results is more complex with a hardware video decoder than a software one. I believe TV browsers (and their media players) tend to treat all random access as if approximate-for-speed is set.

Is it reasonable to require support for approximate-for-speed not being set? If we do then it will need testing as it won't be implemented voluntarily.

**Comment by thasso** [comment]
In general I think it would be beneficial to require support for accurate seeking, especially for Media Applications where the use-case goes beyond "simple" playback. If this is a requirement, the ability to accurately seek can be used to implement things like frame-by-frame view etc.

In case this will not be required, is there a way to query for this capability to find you if a certain device supports accurate seeks?

In any case I think this needs **input from the wider CG membership** to see if this is something that can be made a requirement.

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#7
