### ISSUE TITLE
add WebCodecs to "Web Media APIs proposed to be supported on all platforms"

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#291]
We should consider adding[ WebCodecs](https://www.w3.org/TR/webcodecs/) to "Web Media APIs proposed to be supported on all platforms" in section 5.2.

This is not in caniuse.com [yet](https://github.com/Fyrd/caniuse/issues/5641).
This is implemented in [Chrome](https://www.chromestatus.com/feature/5669293909868544) and [Firefox](https://bugzilla.mozilla.org/buglist.cgi?short_desc_type=allwordssubstr&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&classification=Graveyard&short_desc=WebCodecs&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=INACTIVE&resolution=DUPLICATE&resolution=WORKSFORME&resolution=INCOMPLETE&resolution=SUPPORT&resolution=EXPIRED&resolution=MOVED) but not yet Safari.

**Comment by chrisn** [comment]
WebCodecs isn't implemented in Firefox yet - see [WPT results](https://wpt.fyi/results/webcodecs?label=master&label=experimental&aligned&q=webcodecs). The link you used only shows the merging of WPT into the Firefox source tree.

**Comment by jpiesing** [comment]
> WebCodecs isn't implemented in Firefox yet - see [WPT results](https://wpt.fyi/results/webcodecs?label=master&label=experimental&aligned&q=webcodecs). The link you used only shows the merging of WPT into the Firefox source tree.

Thanks for that correction. It doesn't change the proposal though, section 5 of the WMAS spec is for APIs which are useful for media apps but which are not yet supported on all 3 HTML5 UA codebases. It seems (unfortunately) that WebCodecs is slightly further away from this than I thought. Still it doesn't become eligible to move out of section 5 unless/until Safari would support it.

**Comment by JohnRiv** [comment]
Thanks @jpiesing for raising this. As the "Web Media APIs proposed to be supported on all platforms" section is non-normative, it does not impact implementations nor our test suite if we were to add it. It's more of a public vote of support for it. 

Let's see what other comments come in over the next couple days and then depending on that, I'll do a PR.

**Comment by JohnRiv** [comment]
FYI, I've put up PR #292 for this change. I'm planning to wait until the next HATF meeting on November 10th to move it to Call for Consensus to be sure there is ample time for people to be aware of the proposed change before we merge it.

**Comment by JohnRiv** [comment]
If there are no issues merging, we'll merge on November 24th

**Comment by JohnRiv** [comment]
Merged #292, closing this issue
