### ISSUE TITLE
consider including WASM

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#294]
It has been noted that Amazon use WASM as part of their approach to supporting Prime Video on many devices.

"How Prime Video updates its app for more than 8,000 device types"

https://www.amazon.science/blog/how-prime-video-updates-its-app-for-more-than-8-000-device-types

"By using Wasm instead of JavaScript for certain elements of the Prime Video app, we’ve reduced the average frame times on a mid-range TV from 28 milliseconds to 18. The worst-case frame times also decreased from 40 milliseconds to 25. And in ongoing work we’re driving the frame down still further."

Looking at [caniuse](https://caniuse.com/wasm), this was supported in all desktop browsers since 2017.

We should consider including it in WMAS.

**Comment by louaybassbouss** [comment]
@jpiesing  full support from my side. BTW Wasm is supported on major mobile browsers as well.

**Comment by JohnRiv** [comment]
Great point. The 3 WASM W3C specs became official RECs at the end of 2019, so those would seem to be the best items to reference:

- [WebAssembly Core Specification](https://www.w3.org/TR/wasm-core-1/)
- [WebAssembly JavaScript Interface](https://www.w3.org/TR/wasm-js-api-1/)
- [WebAssembly Web API](https://www.w3.org/TR/wasm-web-api-1/)

**Comment by JohnRiv** [comment]
The Core Web Specifications section where we currently include ECMAScript would be the most appropriate place for these

**Comment by JohnRiv** [comment]
Although WASM has desktop browser support, it is not supported on some 32-bit devices, which some set top boxes are limited to.

**Comment by JohnRiv** [comment]
Given WASM 2.0 is in the works, we should be specific about which version of Web Assembly we include if we include it

**Comment by JohnRiv** [comment]
Given the work to support WASM on STB devices is still ongoing, perhaps including the three WASM 1.0 specs listed above in "Web Media APIs proposed to be supported on all platforms" (under "5.3 Other web specifications") is appropriate for WMAS2022.

**Comment by JohnRiv** [comment]
Based on the conversations from the HATF call on August 17th, here is a proposed update to the "Introduction" section of "Web Media APIs proposed to be supported on all platforms" which could facilitate the three WASM 1.0 specs being added to "5.3 Other web specifications" (additional text in **bold**):

> APIs in this section are important for web media delivery, but **either** are not yet implemented in all four code bases **or not yet implemented across embedded browsers in consumer products**. We encourage the following APIs be implemented on all HTML user agents as soon as possible. It is expected that, as implementations become available, some of these specifications may be listed as supported on all platforms in a future version of this specification.

**Comment by JohnRiv** [comment]
Note, based on discussions in the September 14th HATF call and further follow-up conversations, I've amended the PR to include the word "commonly". It now reads (with the newly inserted text in bold)

> APIs in this section are important for web media delivery, but either are not yet implemented in all four code bases or not yet **commonly** implemented across embedded browsers in consumer products. We encourage the following APIs be implemented on all HTML user agents as soon as possible. It is expected that, as implementations become available, some of these specifications may be listed as supported on all platforms in a future version of this specification.

I'll move the PR to call-for-consensus

**Comment by JohnRiv** [comment]
Closed via #307
