### ISSUE TITLE
Clarify needs for DOM specifications section

### ISSUE THREAD

**Issue by tidoust** [w3c-cg/webmediaapi#3]
Some comments, looking at the [DOM specifications](https://w3c.github.io/webmediaapi/#dom-specifications) section.

DOM4 does not seem to fit in a list of specs that define "standard code values and key values" for "remote control or keyboard key events". Also, it seems weird to reference the key values and code values spec without mentioning "UI Events", their parent spec.

The [Dependencies section](http://www.w3.org/TR/html51/infrastructure.html#conformance-requirements-dependencies) in HTML5.1 specifies that "implementations must support DOM and the events defined in UI Events" (with a reference to DOM4 and UI Events). In turn, the [conformance section](http://www.w3.org/TR/uievents/#conf-interactive-ua) of the UI Events spec requires implementations to support "the complete set of key and code values defined in [UIEvents-Key] and [UIEvents-Code] (subject to platform availability)".

In other words, support for DOM4, UI Events, KeyboardEvent key values and KeyboardEvent code values is de facto required when support for HTML5 is, and could be removed from this API list. If it seems useful to reference these specifications, they could perhaps be mentioned in a note next to the bullet point that requires HTML5.1 support with text such as: "HTML5.1 depends on a number of specifications, whose support is thus needed as well. This includes [DOM4], [UIEvents], [UIEvents-Key] and [UIEvents-Code]".

My understanding is that, by referencing KeyboardEvent key and code values, what you would like to do is to clarify the list of key and code value categories that are particularly relevant for the targeted platform and that implementers should pay particular attention to, the "(subject to platform availability)" that the UI Events spec alludes to. For instance, [Media Keys](http://www.w3.org/TR/uievents-code/#key-media) code values and [Navigation Keys](http://www.w3.org/TR/uievents-key/#keys-navigation), [Device Keys](http://www.w3.org/TR/uievents-key/#keys-device), [Multimedia Keys](http://www.w3.org/TR/uievents-key/#keys-multimedia), etc., key values.

**Comment by mavgit** [comment]
Thanks, @tidoust . I agree with all that.

 If it seems useful to reference these specifications, they could perhaps be mentioned in a note next to the bullet point that requires HTML5.1 support with text such as: "HTML5.1 depends on a number of specifications, whose support is thus needed as well. This includes [DOM4], [UIEvents], [UIEvents-Key] and [UIEvents-Code]".

I like this approach.

> My understanding is that, by referencing KeyboardEvent key and code values, what you would like to do is to clarify the list of key and code value categories that are particularly relevant for the targeted platform and that implementers should pay particular attention to, the "(subject to platform availability)" that the UI Events spec alludes to. For instance, Media Keys code values and Navigation Keys, Device Keys, Multimedia Keys, etc., key values.

Correct. We want to make sure that all input device keys that are sent to the Web app use standard values. For example, any remote control device that has a red colored key results in [ColorF0Red](https://www.w3.org/TR/uievents-key/#keys-media-controller) sent to the application. We want to test for this, so we want the API spec to highlight this requirement.

**Comment by mavgit** [comment]
**Call for consensus:** Replace the content of Section 2.2 with a comment along the following lines:

>HTML5.1 requires support for [DOM4], [UIEvents], [UIEvents-Key] and [UIEvents-Code].
>
>Of particular note, these specs require that client implementors must ensure that all input device keys that are sent to the Web app using standard code values and key values, such as [Media Keys](http://www.w3.org/TR/uievents-code/#key-media) code values and [Navigation Keys](http://www.w3.org/TR/uievents-key/#keys-navigation), [Device Keys](http://www.w3.org/TR/uievents-key/#keys-device), [Multimedia Keys](http://www.w3.org/TR/uievents-key/#keys-multimedia), etc.
>
>For example, any keypress of a red colored key on a remote control device must result in [ColorF0Red](https://www.w3.org/TR/uievents-key/#keys-media-controller) sent to the application.

Please comment if you disagree. Silence is taken as consent.
We'll apply changes after the upcoming F2F.

**Comment by davemevans** [comment]
PR #68 implements text similar to https://github.com/w3c/webmediaapi/issues/3#issuecomment-266919931.

**Call for consensus:** Merge #68 and close issue.

**Comment by davemevans** [comment]
Closed via 30b86c1.

**Comment by davemevans** [comment]
Consensus reached on telco 03/05/17.
