### ISSUE TITLE
Missing key content in Web Media Document

### ISSUE THREAD

**Issue by boyofgreen** [w3c-cg/webmediaapi#30]
Based on some of our earlier discussions, I believe the current document is missing key content for implementers like:
1. Recommendation for updateable runtimes (for both security and features)
2. Implementation best practices on porting run times (like memory utilization, full screen, data storage)
3. Key non-W3C features needed (like support for buttons on a tv remote)

Also, I'd like to recommend we change the name of the doc to "2017 Implementer's Guide" as apposed to Media APIs.  APIs would be a subset of the document.

**Comment by davemevans** [comment]
22/02: There were no objections raised on the call.
Next steps: create some boilerplate to get the document into the state described above.

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#8
