### ISSUE TITLE
Update README references to deprecated documents

### ISSUE THREAD

**Issue by JohnRiv** [w3c-cg/webmediaapi#322]
In the README of this repo we currently state the following:

> [Web Media API Community Group](https://www.w3.org/community/webmediaapi) also maintains repositories for two other specifications:
> - [Web Media Application Developer Guidelines](https://github.com/w3c/webmediaguidelines/)
> - [Web Media User Agent Integration](https://github.com/w3c/webmediaporting)

Both of those are deprecated & no longer being actively worked on, so we should either remove that section, or update the text to be something along the lines of:

> The [Web Media API Community Group](https://www.w3.org/community/webmediaapi) previously maintained repositories for two other specifications that have since been deprecated:
> - [Web Media Application Developer Guidelines](https://github.com/w3c/webmediaguidelines/)
> - [Web Media User Agent Integration](https://github.com/w3c/webmediaporting)

**Comment by chrisn** [comment]
I prefer your latter suggestion, as it keeps a historical record.
