### ISSUE TITLE
consider updating WebGL version to WebGL 2.0

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#338]
I notice from https://caniuse.com/webgl2 that WebGL 2.0 seems to be supported in all browsers.
- Chrome (since 56, Jan 2017)
- Edge (since 79, Jan 2020)
- Safari (since 15, Sep 2021)
- Firefox (since 51, Jan 2017)

**Comment by JohnRiv** [comment]
WebGL 2.0 support was [added to WPE WebKit in v2.40.0 in March 2023](https://wpewebkit.org/release/wpewebkit-2.40.0.html). 

I had some internal discussions around what is involved in supporting WebGL 2.0 other than being on WPE 2.40 or later. There are additional platform requirements, including updating to OpenGL ES 3.0, which has us looking at 2025 for adding WebGL 2.0 support.

**Comment by JohnRiv** [comment]
During the WAVE HATF call on April 17th, we agreed to close this for WMAS2024 and look to potentially include it in WMAS2025
