### ISSUE TITLE
PNG Third Edition support

### ISSUE THREAD

**Issue by JohnRiv** [w3c-cg/webmediaapi#339]
We currently reference [PNG Second Edition](https://github.com/w3c/webmediaapi/issues/335).

[PNG Third Edition](https://www.w3.org/TR/png-3/) is currently in Candidate Recommendation. 

Looking at the [WPT tests for PNG](https://wpt.fyi/results/png) and [Animated PNG](https://wpt.fyi/results/png/apng):

- Chrome & Edge have full support
- Safari supports it [in the latest version of MacOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1862245#c5)
- Firefox does not yet support it, and there are bugs linked from WPT to track them ([1862245](https://bugzilla.mozilla.org/show_bug.cgi?id=1862245) & [1862235](https://bugzilla.mozilla.org/show_bug.cgi?id=1862235))

If Firefox lands support for PNG Third Edition within the next few months, we could consider including it. 

Also worth noting that at present, [caniuse.com](https://caniuse.com/?search=png) and [MDN](https://developer.mozilla.org/en-US/docs/Glossary/PNG) do not have any data around PNG Third Edition support.

@digitaltvguy if you have any additional data points we should reference to be able to confirm PNG Third Edition support in the 4 major browsers, please comment here with that info.

**Comment by JohnRiv** [comment]
The Firefox bugs are still open, so this likely will not be part of WMAS2024.

**Comment by svgeesus** [comment]
> Also worth noting that at present, [caniuse.com](https://caniuse.com/?search=png) and [MDN](https://developer.mozilla.org/en-US/docs/Glossary/PNG) do not have any data around PNG Third Edition support.

For caniuse, see

 - https://github.com/Fyrd/caniuse/issues/7031

Also, PNG 3rd Edition has an implementation report which also covers manual tests and the general implementation landscape, not just automatic browser tests:

 - https://w3c.github.io/PNG-spec/Implementation_Report_3e/
 
 (We should really move that one old apng test in with the [rest of the apng tests](https://wpt.fyi/results/png/apng?label=master&label=experimental&aligned)

**Comment by JohnRiv** [comment]
Thanks for the details @svgeesus! That implementation report is excellent. Looks like Firefox & Safari have a few bugs to work through, so we'll reference those reports to track support from them.

**Comment by JohnRiv** [comment]
We'll close this issue for WMAS2024 and hopefully this can be included in WMAS2025 if the tests pass

**Comment by svgeesus** [comment]
As an update, [Third Edition support has improved](https://w3c.github.io/png/Implementation_Report_3e/). 

- APNG is implemented in Chrome, Edge, Firefox, Safari and Ladybird (it is being implemented in Servo but has not yet landed). 
- CICP is implemented in Chrome, Edge, Firefox, Safari and Ladybird. Not yet in Servo.
- Exif orientation is getting there, some tests depend on still-evolving CSS specs.

Also, on 24 June 2025, [PNG Third Edition became a W3C Recommendation](https://www.w3.org/TR/2025/REC-png-3-20250624/)
