### ISSUE TITLE
Check CSS Snapshot 2017

### ISSUE THREAD

**Issue by tidoust** [w3c-cg/webmediaapi#34]
The CSS Working Group published the [CSS Snapshot 2017](http://www.w3.org/TR/css-2017/) spec. The list we have in the Web Media APIs spec mostly remains unchanged in the new version of the CSS snapshot. The snapshot also has [CSS Writing Modes Level 3](http://www.w3.org/TR/css-writing-modes-3/) which defines in particulal the `writing-mode` property to specify the block flow direction and orientation.

This snapshot (as the previous one) is explicit that the list of specs can be considered stable, but that "inclusion in this profile is based on feature stability only and not on expected use or Web browser adoption".

CSS Transitions, CSS Animations, CSS Flexible Box and CSS Transforms are still listed separately with the following flag: "widely deployed with rough interoperability, but the details are not fully worked out and they need more testing and bugfixing".

In our spec, we may update the reference to the CSS Snapshot 2015 to rather target the CSS Snapshot 2017. We may also want to refine the list based on actual Web browser adoption.

**Comment by mavgit** [comment]
Caniuse says that CSS Writing Modes is supported on our target code bases:'
    http://caniuse.com/#search=css%20writing-mode

I propose we move to reference CSS Snapshot 2017 spec.

**Comment by mavgit** [comment]
Call for consensus to reference CSS Snapshot 2017 spec.
