### ISSUE TITLE
Review new TAG Finding on "The evergreen Web"

### ISSUE THREAD

**Issue by tidoust** [w3c-cg/webmediaapi#39]
W3C's Technical Architecture Group (TAG) recently published a TAG Finding named [The evergreen Web](https://www.w3.org/2001/tag/doc/evergreen-web/), that discusses the need for browsers to stay up-to-date and refrain from subsetting the web platform. The document explicitly mentions "some browsers in TVs" as examples of browsers that voluntarily subset the web platform.

Web Media API CG participants should review this Finding. The group should probably start a discussion with the TAG about the Web Media APIs specification afterwards.

For instance, the Web Media API spec work documents what the web platform is at a given point in time, something that the TAG Finding leaves undefined. AFAICT, the "subsetting" that has been discussed so far is not meant to remove features, but rather to point out features that are not widely available across web browsers, and thus not part of the web platform.

**Comment by jpiesing** [comment]
@tidoust Your last paragraph is 100% right. There is a big difference between subsetting specifications and subsetting features that are really available in deployed web browsers.

**Comment by mavgit** [comment]
As discussed in the call, we expect all have had time to read and understand this TAG finding. Since this issue doesn't propose any changes to the spec, we agreed to close it.
