### ISSUE TITLE
Add IndexedDB in "Other web specifications"?

### ISSUE THREAD

**Issue by tidoust** [w3c-cg/webmediaapi#4]
The [Indexed Database API](https://www.w3.org/TR/IndexedDB/) is widely implemented across browsers and devices. It provides a more powerful persistent storage solution than [Web Storage](https://www.w3.org/TR/webstorage/). Should it be added to the [Other web specifications](https://w3c.github.io/webmediaapi/#other-web-specifications) section?

**Comment by mavgit** [comment]
If this is in synch with the four browser code bases, I support this.

Should we still include Web Storage?

Thanks,
mav

**Comment by jpiesing** [comment]
caniuse.com shows indexdb as being very new in browser code bases other than chrome & chrome for android. Is there such a thing as too new?

**Comment by tidoust** [comment]
@jpiesing I suppose the spec could define "too new", or rather an objective criterion used to select technologies, such as "wide availability across major browsers since at least one year" or "since at least 3 browser versions".

Is it possible to find a browser code base that supports MSE but not IndexedDB in practice?

@mavgit IndexedDB does not replace Web Storage. Developers will use Web Storage for "simple" key-value storage needs, and IndexedDB for database-like needs, e.g. when they need to store content and search through it afterwards.

**Comment by mavgit** [comment]
@jpiesing it looks like the issue with IndexedDB is less newness than incomplete support. According to caniuse, [IndexedDB is only partially supported on IE & Edge](http://caniuse.com/#search=indexeddb):

>Partial support in IE 10 & 11 refers to a number of subfeatures [not being supported](http://codepen.io/cemerick/pen/Itymi).

I'd be fine listing IndexedDB as Recommended rather than Required. But to list it as Required, I'd think someone would need to demonstrate that IndexedDB is functional enough to be usable across _all four_ code bases, despite the missing sub features in IE & Edge.

If not, I recommend keeping it as Recommended for the 2017 version of the API spec.

**Comment by tidoust** [comment]
> I'd be fine listing IndexedDB as Recommended rather than Required. But to list it as Required, I'd think someone would need to demonstrate that IndexedDB is functional enough to be usable across all four code bases, despite the missing sub features in IE & Edge.

I believe lack of support in IndexedDB mostly affects compound keys. That's a pity because it means developers need to stick to simple indexes, but IndexedDB remains very useful without it.

I do not know how to be objective though. "Functional enough" seems to be a judgment call that needs to be made for each and every spec. There will always be features that are not supported across browsers. For instance, while not reported in Can I Use, some MSE features are not supported across browsers (e.g. "live seekable range", and support for `audioTracks`, `videoTracks`). The FullScreen API is another example [flagged as "partially supported"](http://caniuse.com/#search=fullscreen) by Can I Use.

**Comment by mavgit** [comment]
From 1/25 call: Move IndexDB to Required and include note that compound keys is an exception.

**Comment by davemevans** [comment]
@tidoust https://www.w3.org/TR/IndexedDB/ does not define compound keys.
Could you clarify what we text we need to add in our specification in order that all four codebases can provide the required support?

**Comment by tidoust** [comment]
@bbcrddave Right, "compound" seems to be the informal term for that feature. The spec says that a [valid key path](http://www.w3.org/TR/2015/REC-IndexedDB-20150108/#dfn-valid-key-path) can be a "non-empty sequence<DOMString>" and also defines [valid key](http://www.w3.org/TR/2015/REC-IndexedDB-20150108/#dfn-valid-key) which can be an `Array`. This is, I think, what Edge in particular does not support today. This affects operations that can take such keys, typically `createObjectStore`, `createIndex`, and `get`.

I suppose our document could note that "Array [key path](http://www.w3.org/TR/2015/REC-IndexedDB-20150108/#dfn-key-path) and array [keys](http://www.w3.org/TR/2015/REC-IndexedDB-20150108/#dfn-key) are not widely supported yet".

**Comment by jpiesing** [comment]
Isn't making an exception for compound keys the same as subsetting? I think  it's a perfectly reasonable pragmatic thing to do.

**Comment by davemevans** [comment]
08/02: Next steps create PR with exception text similar to https://github.com/w3c/webmediaapi/issues/4#issuecomment-276960988

**Comment by davemevans** [comment]
**Call for consensus:** Merge PR #40.

**Comment by joeyparrish** [comment]
My two cents: Shaka Player is able to use IndexedDB on all major browsers (Chrome, Firefox, Edge, IE, Opera, Safari).  We are able to use it for offline playback in spite of limited implementations on IE, Edge, and Safari.  (We'd still like to see those implementations expanded and bugs in them fixed, but what is out there now is good enough for our purposes.)  At least for our particular use case, IndexedDB as implemented today is good enough.  YMMV.

**Comment by mavgit** [comment]
@joeyparrish Thanks for the super helpful report on implementation experience. This kind of input really gives confidence for API inclusion. 3 questions:

1. Are all the current applications for offline playback of on-demand assets or are some applications for offline playback of live assets (i.e. recording)?

2. Any issues with EME keys for protected content?

3. Any suggestions for additional text in our spec beyond PR #40?

**Comment by thasso** [comment]
> 2. Any issues with EME keys for protected content?

Afaik this is not supported by any Browser/DRM-CDN right now, independent of the API that is used to store the raw stream data. One of the problems here is that the license/key needs to be stored and protect in a way that prevents extraction and moving it to a different devices, among other problems.

**Comment by joeyparrish** [comment]
@mavgit:

1. Shaka Player does not permit the storage of live streams.  We only store on-demand assets for offline playback.

2. We do support protected content offline via EME, given the caveat that to do so, the browser must support persistent sessions in EME.  Currently, only Chrome on ChromeOS supports this, but there is an open bug against Chrome to support persistent sessions on other platforms.  It is apparently a very challenging problem to keep keys secure, as @thasso mentioned.  Because this is layered functionality, though, we simply report to the application if persistent sessions are not supported.  When more browsers/platforms support them, no changes are necessary in JavaScript to enable that feature on those platforms.

3. I have no suggestions on top of #40.
