### ISSUE TITLE
root certificates for TLS

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#45]
Web video providers have found it necessary to specify requirements on TLS root certificates that must be supported.

While some lists are proprietary and/or under NDA, an openly available list was defined by the UK DTG based on a subset of the mozilla list. See here for more information [http://dtg.org.uk/work/DBook_Resources/dtgrootcert.html](http://dtg.org.uk/work/DBook_Resources/dtgrootcert.html) .

Should WAVE say something about this?

**Comment by davemevans** [comment]
> Should WAVE say something about this?

I think it probably should, but I'm not sure how this fits into the HATF work. Shouldn't this be a DPCTF issue?

**Comment by jpiesing** [comment]
> I think it probably should, but I'm not sure how this fits into the HATF work. Shouldn't this be a DPCTF issue?

See my comment elsewhere. Dont' expect DPCTF to address anything other than media-related device capabilities any time soon (ever).

**Comment by jpiesing** [comment]
There are two issues;
- A minimum set of root certificates for inter-operabilty. We could make such a list (others have done - see http://dtg.org.uk/work/DBook_Resources/dtgrootcert.html )
- A maximum set of root certificates for security. While desktop browser vendors will have well established procedures for deciding which certificates they use, do certificates used with device browsers come from the browser vendor or whoever integrates the browser onto the device? HbbTV decided that all root certificates had to be approved for web server authentication on the mozilla list - see http://www.mozilla.org/projects/security/certs/. 

This is a hard topic to address in a specification but we shouldn't do nothing just because it's hard.

**Comment by michelnev** [comment]
This seems like a policy decision for the deployment ecosystem.  Maybe this could be a "should" instead of a "shall" to allow conformance to the security settings of various ecosystems.

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#12
