### ISSUE TITLE
requirements on number of simultaneous HTTP connections

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#46]
Web video providers have found it necessary to make requirements on the number of simultaneous HTTP connections that must be possible.

I believe this was based on devices where HTTP requests for media blocked (or severely delayed) HTTP requests for images, HTML pages, XHR (etc).

Requirements on HTTP connection overhead have also been seen.

Should WAVE say something about this?

**Comment by jpiesing** [comment]
Here's a straw man proposal.
> The device MUST be able to download multiple JavaScript, CSS and image assets concurrently. It MUST also be able to make XHR requests (e.g. to stream media) while performing at least one other HTTP GET request.

**Comment by michelnev** [comment]
@jpiesing your straw man proposal seems reasonable.

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#13
