### ISSUE TITLE
requirements on URL length

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#47]
Web video providers have found it necessary to make requirements that URLs upto a certain length (e.g. 2048 characters) must be supported.

Presumably this was based on experience of devices where some part of the system did not support URLs of this length.

Should WAVE say something about this?

**Comment by michelnev** [comment]
I don't think this particularly matters.  All modern UA support arbitrary length URLs (subject to memory constraints).

**Comment by jpiesing** [comment]
> I don't think this particularly matters. All modern UA support arbitrary length URLs (subject to memory constraints).

I don't know for certain what experience made web video providers find it necessary to specify this but they have. I wonder if it may be URLs handed off from the UA to some other component in the overall system. I can only guess though.
Ideally the WAVE spec would make much/most/all of the existing web video provider specs redundant. Unless some of them are prepared to agree this isn't needed any more then I'd prefer to keep it unless it actually does some harm.

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#14
