### ISSUE TITLE
requirements on graphics resolution for rendering browser UI

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#48]
Web video providers have found it necessary to make requirements on the graphics resolution for rendering the browser UI. Sometimes it might be a minimum (e.g. 1280x720). Sometimes it might be one of a set (e.g. one of 1280x720, 1920x1080, 2560x1440 or 3840x2560). This is different from the actual resolution seen by web apps which might be a logical resolution & not the actual one.

Should WAVE say something about this?

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#15
