### ISSUE TITLE
relationship of graphics resolution and coordinate spaces to video resolution / coordinates

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#49]
Web video providers have found it necessary to make requirements about the relationship between graphics resolution and coordinate spaces to video resolution / coordinates.

If the resolutions are not the same then window.devicePixelRatio may be required with specific values.

Should WAVE say something about this?

**Comment by davemevans** [comment]
devicePixelRatio is defined in [CSSOM-VIEW](https://www.w3.org/TR/cssom-view-1/#dom-window-devicepixelratio). https://github.com/w3c/webmediaapi/issues/12 decided that CSSOM-VIEW was implicitly required via HTML5.1.

@jpiesing is this sufficient or is more work required to close this issue?

**Comment by jpiesing** [comment]
Just requiring te API is not sufficient, something needs to be said about the return values.

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#16
