### ISSUE TITLE
minimum requirements on devices being able to generate certain key events

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#50]
Web video providers have found it necessary to specify minimum requirements that a device must be able to generate at least a minimum set of key events and the constant used to represent them.

A minimum set across all devices might be up / down / left / right / enter / back.
For devices with a classical TV remote control there may be a longer list including play/pause/play-pause/ff/frew/stop and/or colour keys.

This issue is **not** about support for a particular API but about the requirements on the device to generate the constants from that API.

Should WAVE say something about this?

**Comment by jpiesing** [comment]
Here is a straw-man proposal for discussion;
> Devices shall be able to generate at least the following events and shall pass them to web applications as defined by [UIEvents-Key] - up ("ArrowUp"), down ("ArrowDown"), left ("ArrowLeft"), right ("ArrowRight"), enter ("Enter"), back ("GoBack")
> Devices that permit the user to generate the following events (e.g. have by a button on a remote control) shall pass them to web applications as defined by [UIEvents-Key] - red ("ColorF0Red"), green ("ColorF1Green"), yellow ("ColorF2Yellow"), blue ("ColorF3Blue"), stop ("MediaStop"), play ("MediaPlay"), pause ("MediaPause"), play/pause ("MediaPlayPause"), fast forwards ("MediaFastForward"), rewind ("MediaRewind")

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#17
