### ISSUE TITLE
Application loading & transition times

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#53]
Web video providers have found it necessary to make requirements on application loading & transition times.

Should WAVE say something about this?

**Comment by davemevans** [comment]
Do providers say anything concrete, or do they make untestable statements around "acceptable" levels?

How can you stipulate loading times when this may require fetching via the network for example?

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#19
