### ISSUE TITLE
Minimum graphics performance

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#54]
Web video providers and others have found it necessary to make requirements on minimum graphics performance.

- CSS3 animations
- CSS3 transitions
- decoding and rendering full screen images

Should WAVE say something about this?

**Comment by davemevans** [comment]
> Should WAVE say something about this?

Possibly, but it feels like a device performance issue rather than a HATF issue?

**Comment by jpiesing** [comment]
How this fits between HATF and DPCTF has been discussed several times. Realistically this is specific to the browser and DPCTF 1) has no expertise in that area and 2) has its hands full with media-related device capabilities for the forseeable future.

**Comment by jpiesing** [comment]
Here's one part of a solution
> The device MUST be capable of decoding and rendering full screen JPEG/PNGs to screen in < 2s. Video memory MUST be capable of holding the equivalent of 3 full screens at the maximum supported device screen resolution.

**Comment by jpiesing** [comment]
For CSS3, OIPF spent a lot of time on this. It ended up discussing how this performance could reasonably be measured and reverse engineering the specification in order to support the measurement approach. 

The measurement approach used some test programs from Orange - https://github.com/Orange-OpenSource/orangemark . 

The most effective thing to measure was the number of animated objects at a constant frame rate.

These were run on real devices and it seemed the most appropriate scale would be log 2 based. Some operators were accelerated on real hardware and some not.

OIPF ended up defining a couple of performance levels. Each level defined the minimum number of animated objects at 25Hz for a series of graphics operations.

Here is an extract of the OIPF spec with all the details.

[OIPF-AS-R2_Spec-Volume_5_(DAE)_(FINAL)-v2_3-2014-01-24-graphics-performance.pdf](https://github.com/w3c/webmediaapi/files/1008137/OIPF-AS-R2_Spec-Volume_5_.DAE._.FINAL.-v2_3-2014-01-24-graphics-performance.pdf)

**Comment by mavgit** [comment]
This issue was moved to w3c/webmediaporting#20
