### ISSUE TITLE
Support Server-Sent Events/EventSource

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#6]
[EventSource](https://www.w3.org/TR/eventsource/) support would enable more efficient network and and resource usage than polling and long polling, and doesn't require any special protocol handling or serving infrastructure, as e.g. WebSockets does, in order to deliver uni-directional updates to the application.

[Support](http://caniuse.com/#feat=eventsource) is good with only Edge still [considering](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serversenteventseventsource/).

I'll create a PR which can always be rejected if consensus can't be reached on this.

**Comment by davemevans** [comment]
From https://github.com/w3c/webmediaapi/pull/7#issuecomment-263907120 by @boyofgreen:
> Note that Edge doesn't support server side events:
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serversenteventseventsource/
I would recommend we make this a nice to have, not a requirement.

There are several polyfills available for engines which chose not to provide native support, a solution I recall we agreed was acceptable. Whilst none of these provide the network and resource benefits of a native solution, they at least present an API for applications.

The argument above implies that we should only mandate features which have support across the big four engines. This seems like a missed opportunity and that we are essentially just documenting the state of the world today. Hopefully this wider point should be discussed at the F2F (which I am unable to attend :disappointed:)

**Comment by mavgit** [comment]
We included Server-Sent Events in our own requirements because it's useful, but removed it precisely due to lack of support across IE/Edge, which represent significant devices.

A status of "considering" means that it's possible support will never come.

This falls below the threshold of what I think we can includes as a mandate.

**Comment by davemevans** [comment]
>  IE/Edge

Is support for a feature in IE (as apposed to Edge) a requirement? There are several comments on issues here which mention IE.

I imagine we can safely assume that no features will be added to IE which is going to limit progression of this specification beyond the state of the world today (not to mention missing support for some features we have already mandated).

**Comment by mavgit** [comment]
@bbcrddave said:
>Is support for a feature in IE (as apposed to Edge) a requirement? There are several comments on issues here which mention IE.

No. I was just supplying all the info I found for completeness.

My opinion is that we want specs to be supported by the four code bases that are common in consumer products:
- Blink/Chromium
- Edge
- Gecko
- WebKit

I'd like to know if we have consensus on that. I do not include IE in the required list, but reported on it as an FYI.

(I broke this discussion thread into it's own Issue #27 )

**Comment by mavgit** [comment]
@bbcrddave said:
>The argument above implies that we should only mandate features which have support across the big four engines. This seems like a missed opportunity and that we are essentially just documenting the state of the world today. Hopefully this wider point should be discussed at the F2F (which I am unable to attend 😞)

I believe we have two API missions:
1. Document the current portable APIs across the four code bases above (listed as Required), and
2. Persuade for inclusion of new APIs in the four code bases above (listed as Recommended)

I believe the two missions should be kept distinct. The first mission raises the floor and the second mission raises the ceiling.

The first mission is indeed documenting the current state of the world, on a periodic basis. It will be the basis of the WAVE HATF test effort, which will ensure that devices don't use very old versions or errant branches of code bases, which is a recurring issue. This is essentially a rearward-looking mission.

The second, forward-looking mission is to extend the portable APIs to better support media web apps. While it involves:
a. Adding APIs as Recommended
there are also other, more direct ways to influence common APIs, including:
b. Filing Issues and bugs with W3C Working Groups (WGs)
c. Filing issues and bugs with specific code bases (e.g. filing issues with Edge to support EventSource)
d. Writing requirements documents
e. Signing up to edit new WG specifications

I personally don't think declaring not-universally-supported APIs to be Required is an effective way to persuade code bases to actually support those APIs, based on my experience influencing the W3C. I fear it can have the opposite effect of making our API spec branch away from the deployed Web.

**Comment by poolec** [comment]
Face to face 15/12/2016:
Agreed to make this specific API recommended in the 2017 spec.
Not agreed as a general policy - see #27.

**Comment by mavgit** [comment]
Call for consensus on making Server-Sent Events recommended as implemented in PR #29

**Comment by davemevans** [comment]
22/02: Consensus reached on telco.
