### ISSUE TITLE
Fetch

### ISSUE THREAD

**Issue by squapp** [w3c-cg/webmediaapi#60]
Has it been considered to add Fetch API to the networking specifcations?
According to [this](http://caniuse.com/#search=fetch) it is supported by the four major web user agents.
It is required in the context of low-latency streaming, e.g. being able to retrieve sub-segments (or CMAF chunks) before the full segment is transmitted.

**Comment by mavgit** [comment]
@squapp Thanks for pointing this out. I believe it is an oversight.

Not only is the API supported on all of our four target code bases, but caniuse lists no issues. We rely on this API.

I propose a Call for Consensus to add a third MUST requirement to 2.7 Networking specifications:
>- Fetch [FETCH]

This will add the following reference from [Specref](http://www.specref.org/?q=fetch):
>Anne van Kesteren. Fetch Standard. Living Standard. URL: https://fetch.spec.whatwg.org/

**Comment by joeyparrish** [comment]
Adding Fetch LGTM.  Fetch is critical for networking from service workers, which can't use XHR.

**Comment by davemevans** [comment]
Consensus reached on on call 05/04/17.
Next steps: Create and merge PR as detailed in https://github.com/w3c/webmediaapi/issues/60#issuecomment-291677327
