### ISSUE TITLE
What additional web APIs need to be added to the draft Web Media API 2017 spec to support Progressive Web Apps?

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#69]
After a presentation on Progressive Web Apps (PWAs), there was an action item to provide a list of additional web APIs (if any) that need to be added to the draft Web Media API 2017 spec to support Progressive Web Apps. This Issue is where that list should be presented and discussed.

**Comment by davemevans** [comment]
My understanding is:
* [Web App Manifest](https://www.w3.org/TR/appmanifest/)
* [Service Workers](https://w3c.github.io/ServiceWorker/)

Neither of these reaches the bar at which we have been able to require inclusion: http://caniuse.com/#feat=web-app-manifest, http://caniuse.com/#feat=serviceworkers

**Comment by hbengali** [comment]
Thee two APIs cited above are indeed the ones required for PWAs. 

> Neither of these reaches the bar at which we have been able to require inclusion: http://caniuse.com/#feat=web-app-manifest, http://caniuse.com/#feat=serviceworkers

Is there a formalized bar that has been established? Service Workers and Web App Manifest are at the core of the advantages a PWA brings (enabling pre-caching logic and adding an icon to home screen/launcher, respectively).

In addition, we recommend (but not require) the following additional APIs (beyond the ones already included in the existing draft, such as MSE, EME & Fetch) for media centric PWAs:

- [Background Fetch](https://wicg.github.io/background-fetch/)
- [Media Session](https://wicg.github.io/mediasession/)
- [Notifications](https://www.w3.org/TR/notifications/)

Here are a few reference materials about PWAs for those looking to learn more:

1. [Voot.com progressive web app case study](https://developers.google.com/web/showcase/2017/voot)
2. [Reference site Google built out to demonstrate best practices around media PWAs](https://biograf-155113.appspot.com/)
3. [Source for the reference site](https://github.com/googlechrome/sample-media-pwa) 
4. [Developer diaries that walk through the reference media PWA development](https://www.youtube.com/playlist?list=PLNYkxOF6rcIBykcJ7bvTpqU7vt-oey72J)

**Comment by davemevans** [comment]
> Is there a formalized bar that has been established?

Yes - basically it is all four major browser engines. See introduction of https://w3c.github.io/webmediaapi/#required-specifications, and https://github.com/w3c/webmediaapi/issues/27 for discussion.

We can (and do) _recommend_ APIs in the spec that do not meet this level, but not require.

**Comment by hober** [comment]
ISTM that this issue is in a similar boat to the previous issue we had on Shared Workers.

**Comment by mavgit** [comment]
Call for Consensus to add the five APIs above:
- Web App Manifest
- Service Workers
- Background Fetch
- Media Session
- Notifications

Each API will be marked as either:
a) Required iff supported by the 4 code bases, or
b) Recommended, if not.

**Comment by hober** [comment]
I think I don't agree with (b). Like I said above, I don't think the situation with these features is any different from the situation with Shared Workers. I'd be OK with listing them in [APIs not to be tested due to insufficient cross-platform support](https://w3c.github.io/webmediaapi/#apis-not-to-be-tested-due-to-insufficient-cross-platform-support), but recommending them goes too far.

**Comment by jpiesing** [comment]
> I'd be OK with listing them in APIs not to be tested due to insufficient cross-platform support, but recommending them goes too far.

@hober That heading is W3C specs which are mostly implemented across all 4 code bases but where some parts of the spec are not. When a complete W3C spec is not implemented across all 4 code bases then, so far, it's either Recommended or not in the spec at all.

**Comment by hober** [comment]
Ahh. That is different from the shared workers case, where most of the web workers spec is supported by all engines but that specific feature is not. So it makes sense to reference the web workers spec and to specially call out shared workers as not being in the profile.

Given that, I think it makes sense to leave these specs out.

**Comment by davemevans** [comment]
[Web App Manifest](https://www.w3.org/TR/appmanifest/) has a huge warning banner stating that the specification is not stable. Can we really even recommend an API which is noted as being in flux?

**Comment by tidoust** [comment]
To complement @hober's points: _recommended_ still suggests SHOULD statements, which in turn mean the specs would have to appear as normative references, whereas _aspirational_ would mean informational notes with informative references.

It the Web Media APIs spec comes to the W3C Rec track, normative references to specs that are still explicitly flagged as being in flux will be highly frowned upon, and would likely block the advancement of the spec along the Rec track. Informative references would not be a problem.

**Comment by mavgit** [comment]
I agree that we should not be using SHOULD in an incompatible way to the standard meeting.

**Comment by davemevans** [comment]
Consensus reached on 28/06/17 telco to add APIs in https://github.com/w3c/webmediaapi/issues/69#issuecomment-305136736 after refactor has been completed and merged.

**Comment by davemevans** [comment]
Background Fetch does not seem to be implemented in any browser as far as I can tell, and every algorithm in the public specification (https://wicg.github.io/background-fetch/) simply says "TODO".

Personally, I don't think we should even include it in the aspirational list at this stage.

**Comment by mavgit** [comment]
LGTM

**Comment by davemevans** [comment]
Closed via https://github.com/w3c/webmediaapi/pull/85/commits/a25f42dc98d72f59db8d2a37a8504ab42b10ab9c.
