### ISSUE TITLE
Change opening statement around code base support of APIs at publication time

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#70]
During the discussion for https://github.com/w3c/webmediaapi/issues/27, it was suggested that the opening sentence of the Abstract section of the document be changed from:

> This specification defines the Web APIs that should be included in device implementations to support media web apps in 2017. 

to: 

> This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication.

No consensus could be reached on this, and further discussion was requested.

**Comment by jpiesing** [comment]
I think this captures what @mavgit and I had discussed, encouraging browsers in devices to move forwards and not stay on old versions of those code bases.

> This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication. It is recommended that these web APIs be included in device implementations under development in 2017 so that they are available to media web apps from 2018 onwards.

**Comment by mavgit** [comment]
> This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication.

We agree on the first sentence.

>  It is recommended that these web APIs be included in device implementations under development in 2017 so that they are available to media web apps from 2018 onwards.

I think this is close, but I want to point out a few issues:
1. The first sentence is written in a way to be applicable to any annual version of this spec (e.g. "at the time of publication") where the second sentence is specific to this 2017 publication. I think it would be better to be rewritten not specific to a year.
2. By saying "...are available to media web apps from 2018...", implies that there cannot be 2017 products. But of course, it's likely that some desktop browsers may support this spec immediately on publication. So, I don't think there should be an implication of a required delay till first compliant products.
3. By saying "... 2018 onwards" could be read as saying the first spec is supported forever, which may or may not be true.

Those are the issues I'd like to see cleared up. A straw man attempt to address all three is:

>This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication. **It is recommended that device implementations support the most recently published version of this specification at the time of product development.**

**Comment by jpiesing** [comment]
>     The first sentence is written in a way to be applicable to any annual version of this spec (e.g. "at the time of publication") where the second sentence is specific to this 2017 publication. I think it would be better to be rewritten not specific to a year.

Re-writing this to not be specific to a year reduces the impact of the document when used in negotiations with third parties.

>    By saying "...are available to media web apps from 2018...", implies that there cannot be 2017 products. But of course, it's likely that some desktop browsers may support this spec immediately on publication. So, I don't think there should be an implication of a required delay till first compliant products.

That wasn't the intention.

>    By saying "... 2018 onwards" could be read as saying the first spec is supported forever, which may or may not be true.

That is an important point which should be brought out explicitly.

I'll try & make a proposal later.

**Comment by davemevans** [comment]
Do we have a proposal for this yet?

**Comment by jpiesing** [comment]
Here's an attempt at a compromise.

> This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication. 
> One goal for this specification is encouraging and enabling faster adoption of new web standards in those device ecosystems that are often slow to do so (e.g. TV receivers). It is hoped that this specification can be used as a reference by those specifying which web APIs are to be included in device implementations under development in the year after publication.

**Comment by mavgit** [comment]
> One goal for this specification is encouraging and enabling faster adoption of new web standards in those device ecosystems that are often slow to do so (e.g. TV receivers).

This is great new language and I have no changes. 

> It is hoped that this specification can be used as a reference by those specifying which web APIs are to be included in device implementations under development in the year after publication.

I also agree with this statement about use our spec as a reference for implementations, but we should avoid stating any specific time frames for using our spec, like "the year after publication", because:

1. We may decide to publish a new spec in less than a year (e.g. if Service Workers are supported in all code bases in six or nine months).

2. It is moving from writing specifications to coordinating the usage of specifications by manufacturers. We should publish our specs when we need to and it's up to each manufacturer to independently decide if, when and which version of our spec to require. If any manufacturer wishes to require our spec for a year, they are free to do so.

So, I propose simply deleting the last seven words from your proposal:

> This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication.
One goal for this specification is encouraging and enabling faster adoption of new web standards in those device ecosystems that are often slow to do so (e.g. TV receivers). It is hoped that this specification can be used as a reference by those specifying which web APIs are to be included in device implementations.

**Comment by jpiesing** [comment]
To me, our message is much, much weaker if we don't say something about specific time frames.

**Comment by mavgit** [comment]
In order to meet both Jon's interest in a description of when this spec is expected to be used and also meet my concern that we not be prescriptive of the timeframe, I suggest adding a descriptive sentence to my previous proposal.

> This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication.
One goal for this specification is encouraging and enabling faster adoption of new web standards in those device ecosystems that are often slow to do so (e.g. TV receivers). It is hoped that this specification can be used as a reference by those specifying which web APIs are to be included in device implementations. **_Devices and media web apps supporting this spec are expected to be available during the year after publication._**

**Comment by davemevans** [comment]
@jpiesing does this address your concern?

**Comment by jpiesing** [comment]
@mavgit I understand your proposal but it really doesn't help people in manufacturers who want to promote support for the Web Media API spec within their company and with their suppliers. Let me see if I can find something.

**Comment by davemevans** [comment]
@jpiesing took an action on 12/07/17 telco to provide some text for discussion.

**Comment by jpiesing** [comment]
I think this part is agreed from earlier in the discussion;

> This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication.
One goal for this specification is encouraging and enabling faster adoption of new web standards in those device ecosystems that are often slow to do so (e.g. TV receivers). It is hoped that this specification can be used as a reference by those specifying which web APIs are to be included in device implementations.

How about this on the end;
> While some devices and ecosystems may adopt this specification more quickly, a specific target for this version of the specification is products being specified in 2017 and early 2018 for market introduction in 2018 or early 2019.

Or this one;
> While some devices and ecosystems may adopt this specification more quickly, device manufacturers are encouraged to reference this specification when selecting the HTML5 UA for products being specified in 2017 and early 2018 aimed at market introduction in 2018 or early 2019.

**Comment by mavgit** [comment]
I appreciate you proposing additional alternative language, but to me these both still take us out of what should be in a technical spec because they involve coordinating product shipping plans and as such I can't agree to including it in this spec.

**Comment by jpiesing** [comment]
> I appreciate you proposing additional alternative language, but to me these both still take us out of what should be in a technical spec because they involve coordinating product shipping plans and as such I can't agree to including it in this spec.

Sorry but I really don't understand this objection. How can it be OK for the document to encourage the code bases to support the recommended APIs but not to encourage manufacturers to support the list of APIs in the document. I really don't see any difference here. What am I missing?

**Comment by mavgit** [comment]
>How can it be OK for the document to encourage the code bases to support the recommended APIs but not to encourage manufacturers to support the list of APIs in the document.

There is no problem with either encouraging the code bases to support the recommended APIs or with encouraging manufacturers to support the list of APIs in the document.

I proposed the following language in issue #95:
> We strongly propose that the following APIs be implemented on all HTML user agents as soon as possible.

I would be happy to extend that statement to manufacturers:
> We strongly propose that the following APIs be implemented on all HTML user agents **and delivered in products by manufacturers** as soon as possible.

The difference between the above statements and your [proposed changes](https://github.com/w3c/webmediaapi/issues/70#issuecomment-315049604) is the inclusion of specific timeframes for product introduction into the market place:
- "a specific target for this version of the specification is products being specified in 2017 and early 2018 for market introduction in 2018 or early 2019."
- "for products being specified in 2017 and early 2018 aimed at market introduction in 2018 or early 2019."

It is fine to encourage adoption of specs by code bases and by manufacturers "as soon as possible", but coordinating the specific timeframes when supporting products will be introduced into the market is not done in W3C and other technical specifications that I'm familiar with.

Moreover, we haven't had any discussion of product introduction plans by manufacturers, so we don't have an agreement to back up these statements.

My suggestion is we leave out of this specification any mention of specific timeframes for product introduction into the market. After we've published this specification and after manufacturers have had a chance to compare this specification with their product roadmaps, then manufacturers may choose to make a statement on product support timeframes as part of WAVE or some other forum.

**Comment by jpiesing** [comment]
@mavgit 

> It is fine to encourage adoption of specs by code bases and by manufacturers "as soon as possible", but coordinating the specific timeframes when supporting products will be introduced into the market is not done in W3C and other technical specifications that I'm familiar with.
> 

I strongly disagree that this is any form of coordination. IMHO expressing the aspiration that this spec be included in 2018 products is not coordination.

> Moreover, we haven't had any discussion of product introduction plans by manufacturers, so we don't have an agreement to back up these statements.
> 

And I suspect anti-trust law would not permit that kind of discussion even if manufacturers would say anything - which they won't.

> My suggestion is we leave out of this specification any mention of specific timeframes for product introduction into the market. After we've published this specification and after manufacturers have had a chance to compare this specification with their product roadmaps, then manufacturers may choose to make a statement on product support timeframes as part of WAVE or some other forum.
> @jpiesing

See my previous comment.

**Comment by mavgit** [comment]
>I strongly disagree that this is any form of coordination. IMHO expressing the aspiration that this spec be included in 2018 products is not coordination.

Putting aside any legal issue, I don't share the specific aspiration that this spec be included in 2018 products. I feel we publish the spec and voluntary adoption happens according to the market, whether before, during or after 2018.

I agree with the following statement proposed in original statement in @bbcrddave [opening comment](https://github.com/w3c/webmediaapi/issues/70#issue-227906423) to be factually true and should be included in any case:

>This specification defines the Web APIs to support media web apps that are supported across all four of the most widely used user agent code bases at the time of publication.

I could also support a general _additional_ statement like:
> We encourage manufacturers to develop products that support the APIs in the most recent version of Web Media API Snapshot.

I can't support any statements with specific dates of API adoption or product introduction.

If we can't agree on a variant of the second sentence, I think we should include the first sentence, since it is a clear statement of fact about this spec.

**Comment by davemevans** [comment]
A number of dates are mentioned in the Introduction to Section 2. We should probably also address that text as part of this discussions.

Edit: The original issue was about the Abstract, but has expanded to include the Introduction to Section 2.

**Comment by davemevans** [comment]
Consensus reached on 18/07/17 telco to implement https://github.com/w3c/webmediaapi/issues/70#issuecomment-316089816. This is a change to the Abstract.

A corresponding change will also be required to Section 2 Introduction..
