### ISSUE TITLE
consider expanding the introduction with diagram from slides 7/8/9 of 2017-05-31 HATF phone conf

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#72]
The diagram that builds up across slides 7, 8 and 9 of the slides for the 31st May 2017 HATF phone conference helps set this specification in context. Please consider adding it (or a derivative) to the introduction of the specification.

**Comment by davemevans** [comment]
The document needs a proper Introduction.

Among other things (including the above) it should probably mention that we will develop tests to confirm compliance against the Required Specifications etc.

**Comment by mavgit** [comment]
@jpiesing 
>The diagram that builds up across slides 7, 8 and 9 of the slides for the 31st May 2017 HATF phone conference helps set this specification in context. Please consider adding it (or a derivative) to the introduction of the specification.

Here is the referenced diagram:
![web media specs](https://user-images.githubusercontent.com/4162164/27754698-8e60fa48-5da0-11e7-9ff0-3b3ddc519c53.png)

The diagram describes all three of the specs being developed by the Web Media API CG.

So, I suppose this could be used in the introduction to this and the other two specs by highlighting the row pertaining to the specific spec like this:
![web media specs 2](https://user-images.githubusercontent.com/4162164/27754751-d0561b2c-5da0-11e7-8dc7-0427d7269f59.png)

In addition, there would need to be some additional text explaining the diagram.

Do people think that would be a good addition to this spec?

**Comment by jpiesing** [comment]
I think it could work with some text explaining that this is one of 3 specifications each addressing a different layer in the software stack and each having a different audience. The "Device Layers" column in the diagram could then be renamed "Software Stack Layer" and the "Developer" column renamed to "Audience". Moving "HATF Spec" to the left hand side might help as well.

**Comment by mavgit** [comment]
>The "Device Layers" column in the diagram could then be renamed "Software Stack Layer" and the "Developer" column renamed to "Audience". Moving "HATF Spec" to the left hand side might help as well.

Made those changes. Not sure "Audience" is perfect, but it's better than "Developer". Also switched column title from HATF to CG, since the CG is where specs are published.

![web media specs 3](https://user-images.githubusercontent.com/4162164/27926212-73c7a254-623c-11e7-9e86-60d6f596332f.png)

**Comment by jpiesing** [comment]
@mavgit Would "target audience" be any better than just plain "audience"?

**Comment by mavgit** [comment]
>Would "target audience" be any better than just plain "audience"?

Done.

![web media specs 5](https://user-images.githubusercontent.com/4162164/28103780-55992b6e-668c-11e7-94f4-e18983ca4fa5.png)

**Comment by mavgit** [comment]
I'm not sure whether nor exactly how this diagram integrates into the spec, but I did add it to the [CG home page](https://www.w3.org/community/webmediaapi/).

**Comment by jpiesing** [comment]
Would it be any better with the column titles at the top rather than the bottom?

**Comment by davemevans** [comment]
Consensus reached on 12/07/17 telco not to include this diagram for now. We may revisit this when we come to publish the final document.
