### ISSUE TITLE
point out that future versions of the spec may drop APIs or parts of

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#77]
In the discussions in #70, @mavgit made the point that:
> "By saying "... 2018 onwards" could be read as saying the first spec is supported forever, which may or may not be true."

I think this is worth calling out explicitly. I suggest adding the following, either on the end of the first paragraph of the abstract or as a new paragraph.

> Specifications that are required in this version of this specification may fall out of use in the web and be dropped in whole or in part from some web platforms. Hence a specification being "Required" in this version of this specification does not guarantee that it will remain "Required" in future versions of this specification.

**Comment by mavgit** [comment]
I agree with adding this to the introduction.

**Comment by davemevans** [comment]
This seems like a reasonable addition to me.

**Comment by davemevans** [comment]
**Call for consensus**: Add the text in https://github.com/w3c/webmediaapi/issues/77#issue-238461393 to the introduction.

**Comment by davemevans** [comment]
Proposed PR #86 implements the text in https://github.com/w3c/webmediaapi/issues/77#issue-238461393.

**Comment by davemevans** [comment]
Consensus reached on 12/07/17 telco to add this text.

**Comment by davemevans** [comment]
Fixed via https://github.com/w3c/webmediaapi/commit/984813458c46958e0722f952223c438909eb4e99.
