### ISSUE TITLE
Does our ISO Common Encryption reference need to be updated for CMAF?

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#78]
There is currently an editor's note in the Media Specifications section of Required Specifications saying:

> The ISO Common Encryption [[!eme-stream-mp4]] reference may need to be updated for MPEG CMAF.

Can someone up to speed on the matter confirm what, if any, change is needed to our specification or whether this note can be removed?

**Comment by davemevans** [comment]
**Call for consensus:** Delete this editor's note.

**Comment by jpiesing** [comment]
This is not an objection but an observation. If someone thinks that "ISO Common Encryption ('cenc') Protection Scheme for ISO Base Media File Format Stream Format" (https://w3c.github.io/encrypted-media/format-registry/stream/mp4.html) may need updating for CMAF then perhaps an issue should be opened in the EME github?

**Comment by davemevans** [comment]
Proposed PR #82 implements this.

**Comment by mavgit** [comment]
>If someone thinks that "ISO Common Encryption ('cenc') Protection Scheme for ISO Base Media File Format Stream Format" (https://w3c.github.io/encrypted-media/format-registry/stream/mp4.html) may need updating for CMAF then perhaps an issue should be opened in the EME github?

FYI: When I wrote that note, I didn't mean that the existing "ISO Common Encryption..." spec needs to be updated. That spec remains fine as-is for DASH. I meant that the reference in our spec may need to be changed to refer to a brand new doc - not yet written - describing the file encryption scheme for CMAF. It's not clear to me who will write that new spec.

**Comment by jpiesing** [comment]
> FYI: When I wrote that note, I didn't mean that the existing "ISO Common Encryption..." spec needs to be updated. That spec remains fine as-is for DASH. I meant that the reference in our spec may need to be changed to refer to a brand new doc - not yet written - describing the file encryption scheme for CMAF. It's not clear to me who will write that new spec.

The chain of references goes from EME itself to "Encrypted Media Extensions Stream Format Registry" to "ISO Common Encryption ('cenc') Protection Scheme for ISO Base Media File Format Stream Format" to CENC itself, i.e. there are two intermediate W3C specs between EME and CENC. What I thought you were suggesting was that CMAF's encryption might need adding to one of the two intermediate W3C specs.

**Comment by mavgit** [comment]
>What I thought you were suggesting was that CMAF's encryption might need adding to one of the two intermediate W3C specs.

I think there would need to be an additional spec in parallel to "ISO Common Encryption ('cenc') Protection Scheme for ISO Base Media File Format Stream Format" that would cover the encryption details from the CMAF spec. This document would then be added as a new entry into the registry in Encrypted Media Extensions Stream Format Registry.

FYI, there is a parallel registry for MSE, which would also require a new spec for CMAF.

**Comment by mavgit** [comment]
Call for Consensus: Remove ISO Common Encryption ('cenc') Protection Scheme for ISO Base Media File Format Stream Format [eme-stream-mp4] from spec list, since already referenced by the EME spec.
