### ISSUE TITLE
Remove text around polyfills

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#80]
#65 implemented some text about polyfills (as discussed in https://github.com/w3c/webmediaapi/issues/27).

It has been pointed out that the current text
> Where an API is made available by a polyfill, responsibility for providing the polyfill lies with the developer.

doesn't really add anything in what is essentially a browser specification, since polyfills are never provided by the browser to make an API available.

Obviously developers can choose to work around a missing feature using a polyfill.

Should we remove this text or reword it?

**Comment by mavgit** [comment]
I agree that this sentence doesn't add anything, so should be removed.

**Comment by michelnev** [comment]
I agree as well, we can remove that sentence.

**Comment by davemevans** [comment]
**Call for consensus:** Remove this sentence from the text.

**Comment by davemevans** [comment]
Proposed PR #83 implements this.

**Comment by mavgit** [comment]
LGTM

**Comment by davemevans** [comment]
Consensus reached on 12/07/17 telco to remove text.

**Comment by davemevans** [comment]
Closed via https://github.com/w3c/webmediaapi/commit/9db470c47f8d9ecdab820024fec5980d4adaa7af
