### ISSUE TITLE
Replace 'Recommended' with a synonym in Section 3 title

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#84]
In https://github.com/w3c/webmediaapi/pull/76#issuecomment-311684073, @mavgit said:
> Given @tidoust comment (#69 (comment)) that "recommended still suggests SHOULD statements", the section should not be entitled "Recommended specifications", but something more "aspirational".

We should find a synonym to replace Recommended in the title of section 3.

**Comment by jpiesing** [comment]
If nobody comes up with a good idea then I would suggest sticking with "Recommended" but avoid normative references. If that means using "may" in the body of the text then so be it.

IMHO requiring "should" statements to use normative references is strange but if that's W3C policy / practice then so be it. Other places define normative references as "documents to which conformance is necessary to claim compliance to the deliverable containing the reference". A should is clearly not "necessary".

**Comment by mavgit** [comment]
We could switch the two sections titles to something more descriptive, like:
1. "Web Media APIs supported on all platforms"
2. "Web Media APIs supported on some platforms"

**Comment by mavgit** [comment]
Just to be clear on the section numbering, I'm proposing only changes to the titles of sections 2 & 3:

1. Introduction _(no change)_
2. Required specifications _->_ Web Media APIs supported on all platforms
3. Recommended specifications _->_ Web Media APIs supported on some platforms

Note that all the actual requirements language (i.e. **must** statements) in section 2 would be unchanged. Therefore, the title change has no effect on the actual spec requirements.

**Comment by mavgit** [comment]
Actually, calling the APIs "Web Media APIs" is not right, since many of the APIs have nothing to do with media. They are all web APIs, so I propose the sections be titled:

1. Introduction
2. Web APIs supported on all platforms
3. Web APIs supported on some platforms

**Comment by jpiesing** [comment]
> Actually, calling the APIs "Web Media APIs" is not right, since many of the APIs have nothing to do with media. They are all web APIs, so I propose the sections be titled:
> 
>     Introduction
>     Web APIs supported on all platforms
>     Web APIs supported on some platforms

Do we really want to lose the aspirational element completely?

**Comment by mavgit** [comment]
>Do we really want to lose the aspirational element completely?

OK. In order to include aspiration without using the word "recommend", how about something like:

>1. Introduction
>2. Web Media APIs currently supported on all platforms
>3. Web Media APIs **urged** to be supported on all platforms

or, softer:

>1. Introduction
>2. Web Media APIs currently supported on all platforms
>3. Web Media APIs **proposed** to be supported on all platforms

**Comment by mavgit** [comment]
Call for Consensus

>1. Introduction
>2. Web Media APIs currently supported on all platforms
>3. Web Media APIs proposed to be supported on all platforms

**Comment by davemevans** [comment]
Fixed via https://github.com/w3c/webmediaapi/commit/7028c52f61d588e27f33f62e8f4544dbbee8671b.
