### ISSUE TITLE
Add a "Participate: File an issue (open issues)" section to the top of the spec

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#87]
To make it easier to get comments when the spec goes out for review, please add to the headers, after the authors:

>**Participate:**
   [File an issue](https://github.com/w3c/webmediaapi/issues/new) ([open issues](https://github.com/w3c/webmediaapi/issues))

See [HTML 5.1](https://www.w3.org/TR/html51/) spec for the model.

**Comment by davemevans** [comment]
ReSpec works slightly differently to Bikeshed, but the [`github`](https://github.com/w3c/respec/wiki/github) option in ReSpec handily does much the same:

>**Participate:**
> [GitHub w3c/webmediaapi](https://github.com/w3c/webmediaapi)
> [File a bug](https://github.com/w3c/webmediaapi/issues)
> [Commit history](https://github.com/w3c/webmediaapi/commits/gh-pages)

**Comment by mavgit** [comment]
LGTM. This should encourage reviewers to file issues.

**Comment by mavgit** [comment]
Since this is purely editorial, it can be merged in with CfC.
