### ISSUE TITLE
Change spec title to "Web Platform Snapshot 2017"

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#88]
Looking at the draft spec, after we have split out two areas into separate specs, it would be more accurate to call this spec the _Web Platform Snapshot 2017_ instead of _Web Media APIs 2017_.

1. This follows the model of the [CSS Snapshot 2017](https://www.w3.org/TR/css-2017/), which we reference for the CSS part of our spec. We are essentially extending the CSS Snapshot to cover the entire Web Platform, hence it's a Web Platform Snapshot.
2. _Web Media API_ implies this is a different platform than the mainstream "Web Platform", but it isn't. All the APIs in this spec are part of the Web Platform. This has been a repeated point of confusion and unnecessary controversy.
3. _Web Media API_ implies that these are all _media_ APIs. In fact, the vast majority of the APIs in this spec are not media related. 
4. Media web apps run on standard Web browsers today. That was one of the main accomplishments of HTML5.

**Comment by jpiesing** [comment]
I see two issues with this proposal;
- The APIs were selected as those most relevant for media web apps. It doesn't attempt to be a complete snapshot.
- The charter of the group was to produce something relevant for media apps and devices. Producing something with apparently a much wider scope may be controversial and/or may delay getting the spec done.

**Comment by mavgit** [comment]
I certainly wasn't trying to change the spec or CG scope, so I'll remove that part of the proposal.

What would we think about:

>Web Media API Snapshot 2017

I think "Snapshot" adds the message that we are presenting a picture of which Web Media APIs are currently supported across all platforms. It also follows the naming of CSS Snapshot 2017, which may help reviewers understand our intentions.

**Comment by jpiesing** [comment]
That works for me.

**Comment by mavgit** [comment]
Call for Consensus

Change title to:
> Web Media API Snapshot 2017

**Comment by davemevans** [comment]
Consensus reached on telco 12/07/17 to change title.
