### ISSUE TITLE
Update intro to section 3 to replace conformance sentence.

### ISSUE THREAD

**Issue by mavgit** [w3c-cg/webmediaapi#95]
In issue #84, we changed the title of section 3 from "Recommended APIs" to "Web Media APIs proposed to be supported on all platforms" to remove the normative language implied by usage of the key word "**Recommended**".

Likewise, the sentence on conformance in the following paragraph needs to be changed to remove the red highlighted conformance key word "**may**" and also because this section has nothing to do with conformance and won't be part of the conformance tests.

Current text: 
>3. Web Media APIs proposed to be supported on all platforms
>
>APIs in this section represent desired functionality that is important for web media delivery, but is not yet implemented widely enough to be Required. **Devices may be conforming implementations of the specifications listed below.** It is expected that, as implementations become available, some of these specifications may become Required Specifications in a future version of this specification.

Proposed revised text: 
>3. Web Media APIs proposed to be supported on all platforms
>
>APIs in this section represent functionality that is important for web media delivery, but is not yet implemented widely enough to be Required. **We strongly propose that the following APIs be implemented on all HTML user agents as soon as possible.** It is expected that, as implementations become available, some of these specifications may become Required Specifications in a future version of this specification.

**Comment by davemevans** [comment]
LGTM.

**Comment by jpiesing** [comment]
I see nothing wrong with "may" in this context, "Devices may be conforming implementations of the specifications listed below" is a statement of fact.

**Comment by mavgit** [comment]
>I see nothing wrong with "may" in this context, "Devices may be conforming implementations of the specifications listed below" is a statement of fact.

While the sentence may be accurate in plain language, there are three issues motivating changing this sentence in the context of this specification:

1. The word "may" has specific meaning when used in a specification, based on [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt). This is why it is automatically red highlighted. We removed the word "recommended" from this section title for the same reason.

2. The phrase "conforming implementations" implies that this section is somehow related to the conformance of this specification. There is no conformance or testable content in this section. Eliminating mention of conformance will avoid confusion.

3. There is nothing in this sentence or this paragraph that clearly explains that the purpose of listing these additional specifications is to encourage HTML code bases to adopt these specifications. That is why I'm proposing to replace this potentially confusing sentence with a clear statement of purpose:

>We strongly propose that the following APIs be implemented on all HTML user agents as soon as possible.

**Comment by jpiesing** [comment]
>     There is nothing in this sentence or this paragraph that clearly explains that the purpose of listing these additional specifications is to encourage HTML code bases to adopt these specifications. That is why I'm proposing to replace this potentially confusing sentence with a clear statement of purpose:
> 
>     We strongly propose that the following APIs be implemented on all HTML user agents as soon as possible.

I like "encourage" as used it in the discussion better than "strongly propose" as used in the proposal.

How about;
> We encourage the following APIs be implemented on all HTML user agents as soon as possible.

**Comment by mavgit** [comment]
I like "encourage" much better. The phrase "strongly propose" sounded awkward.

Call for Consensus on replacing:
> Devices may be conforming implementations of the specifications listed below.

with
> We encourage the following APIs be implemented on all HTML user agents as soon as possible.

**Comment by davemevans** [comment]
Consensus reached on telco 18/07/17 to replace text as described in https://github.com/w3c/webmediaapi/issues/95#issuecomment-316074701.
